import type { Booth, BoothLocation, ScheduleItem } from "./types";

export const locations: BoothLocation[] = [
  {
    id: "a01",
    campus: "campus1",
    code: "A01",
    latitude: 37.546426,
    longitude: 126.964381,
    mapPosition: { x: 50.3157, y: 36.7139},
    mapSize: { width: 44, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a02",
    campus: "campus1",
    code: "A02",
    latitude: 37.546426,
    longitude: 126.964434,
    mapPosition: { x: 53.1901, y: 36.7139},
    mapSize: { width: 43, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a03",
    campus: "campus1",
    code: "A03",
    latitude: 37.546426,
    longitude: 126.964486,
    mapPosition: { x: 56.1043, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a04",
    campus: "campus1",
    code: "A04",
    latitude: 37.546426,
    longitude: 126.964538,
    mapPosition: { x: 58.9754, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a05",
    campus: "campus1",
    code: "A05",
    latitude: 37.546426,
    longitude: 126.964591,
    mapPosition: { x: 61.8718, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a06",
    campus: "campus1",
    code: "A06",
    latitude: 37.546426,
    longitude: 126.964643,
    mapPosition: { x: 64.7237, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a07",
    campus: "campus1",
    code: "A07",
    latitude: 37.546426,
    longitude: 126.964695,
    mapPosition: { x: 67.6160, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a08",
    campus: "campus1",
    code: "A08",
    latitude: 37.546426,
    longitude: 126.964748,
    mapPosition: { x: 70.4741, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a09",
    campus: "campus1",
    code: "A09",
    latitude: 37.546426,
    longitude: 126.9648,
    mapPosition: { x: 73.3260, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a10",
    campus: "campus1",
    code: "A10",
    latitude: 37.546426,
    longitude: 126.964852,
    mapPosition: { x: 76.0673, y: 36.7139},
    mapSize: { width: 42, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a11",
    campus: "campus1",
    code: "A11",
    latitude: 37.546426,
    longitude: 126.964904,
    mapPosition: { x: 78.8076, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a12",
    campus: "campus1",
    code: "A12",
    latitude: 37.546426,
    longitude: 126.964957,
    mapPosition: { x: 81.6683, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a13",
    campus: "campus1",
    code: "A13",
    latitude: 37.546426,
    longitude: 126.965009,
    mapPosition: { x: 84.5383, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a14",
    campus: "campus1",
    code: "A14",
    latitude: 37.546426,
    longitude: 126.965061,
    mapPosition: { x: 87.4142, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "b01",
    campus: "campus1",
    code: "B01",
    latitude: 37.546426,
    longitude: 126.963746,
    mapPosition: { x: 23.5817, y: 36.7139},
    mapSize: { width: 51, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b02",
    campus: "campus1",
    code: "B02",
    latitude: 37.546426,
    longitude: 126.963814,
    mapPosition: { x: 27.2226, y: 36.7139},
    mapSize: { width: 51, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b03",
    campus: "campus1",
    code: "B03",
    latitude: 37.546426,
    longitude: 126.963882,
    mapPosition: { x: 30.8021, y: 36.7139},
    mapSize: { width: 49, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b04",
    campus: "campus1",
    code: "B04",
    latitude: 37.546426,
    longitude: 126.96395,
    mapPosition: { x: 34.2495, y: 36.7139},
    mapSize: { width: 49, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b05",
    campus: "campus1",
    code: "B05",
    latitude: 37.546426,
    longitude: 126.964018,
    mapPosition: { x: 37.6408, y: 36.7139},
    mapSize: { width: 49, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b06",
    campus: "campus1",
    code: "B06",
    latitude: 37.546426,
    longitude: 126.964086,
    mapPosition: { x: 40.9615, y: 36.7139},
    mapSize: { width: 48, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "c01",
    campus: "campus1",
    code: "C01",
    latitude: 37.545951,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 44.3192},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c02",
    campus: "campus1",
    code: "C02",
    latitude: 37.545906,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 47.5207},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c03",
    campus: "campus1",
    code: "C03",
    latitude: 37.545861,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 50.7152},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c04",
    campus: "campus1",
    code: "C04",
    latitude: 37.545816,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 53.8589},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c05",
    campus: "campus1",
    code: "C05",
    latitude: 37.545771,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 56.9810},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c06",
    campus: "campus1",
    code: "C06",
    latitude: 37.545726,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 60.1198},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c07",
    campus: "campus1",
    code: "C07",
    latitude: 37.545681,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 63.2759},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c08",
    campus: "campus1",
    code: "C08",
    latitude: 37.545636,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 66.3672},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c09",
    campus: "campus1",
    code: "C09",
    latitude: 37.545592,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 69.4824},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c10",
    campus: "campus1",
    code: "C10",
    latitude: 37.545547,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 72.6074},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c11",
    campus: "campus1",
    code: "C11",
    latitude: 37.545502,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 75.7324},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c12",
    campus: "campus1",
    code: "C12",
    latitude: 37.545457,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 78.8574},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "d01",
    campus: "campus1",
    code: "D01",
    latitude: 37.545412,
    longitude: 126.964522,
    mapPosition: { x: 32.8255, y: 79.3408},
    mapSize: { width: 51, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d02",
    campus: "campus1",
    code: "D02",
    latitude: 37.545412,
    longitude: 126.964595,
    mapPosition: { x: 36.3021, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d03",
    campus: "campus1",
    code: "D03",
    latitude: 37.545412,
    longitude: 126.964668,
    mapPosition: { x: 39.7917, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d04",
    campus: "campus1",
    code: "D04",
    latitude: 37.545412,
    longitude: 126.964741,
    mapPosition: { x: 43.2617, y: 79.3408},
    mapSize: { width: 49, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d05",
    campus: "campus1",
    code: "D05",
    latitude: 37.545412,
    longitude: 126.964813,
    mapPosition: { x: 46.7122, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d06",
    campus: "campus1",
    code: "D06",
    latitude: 37.545412,
    longitude: 126.964886,
    mapPosition: { x: 50.1432, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d07",
    campus: "campus1",
    code: "D07",
    latitude: 37.545412,
    longitude: 126.964959,
    mapPosition: { x: 53.6068, y: 79.3408},
    mapSize: { width: 49, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d08",
    campus: "campus1",
    code: "D08",
    latitude: 37.545412,
    longitude: 126.965032,
    mapPosition: { x: 57.0638, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "e01",
    campus: "campus2",
    code: "E01",
    latitude: 37.544311,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 44.9121},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e02",
    campus: "campus2",
    code: "E02",
    latitude: 37.544346,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 48.4863},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e03",
    campus: "campus2",
    code: "E03",
    latitude: 37.54438,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 52.0508},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e04",
    campus: "campus2",
    code: "E04",
    latitude: 37.544415,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 55.7129},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e05",
    campus: "campus2",
    code: "E05",
    latitude: 37.54445,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 59.2969},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e06",
    campus: "campus2",
    code: "E06",
    latitude: 37.544485,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 62.8906},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e07",
    campus: "campus2",
    code: "E07",
    latitude: 37.54452,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 66.6016},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e08",
    campus: "campus2",
    code: "E08",
    latitude: 37.544555,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 70.3027},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e09",
    campus: "campus2",
    code: "E09",
    latitude: 37.54459,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 74.0332},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e10",
    campus: "campus2",
    code: "E10",
    latitude: 37.544625,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 77.7734},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e11",
    campus: "campus2",
    code: "E11",
    latitude: 37.544311,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 44.9121},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e12",
    campus: "campus2",
    code: "E12",
    latitude: 37.544346,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 48.4863},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e13",
    campus: "campus2",
    code: "E13",
    latitude: 37.54438,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 52.0508},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e14",
    campus: "campus2",
    code: "E14",
    latitude: 37.544415,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 55.7129},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e15",
    campus: "campus2",
    code: "E15",
    latitude: 37.54445,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 59.2969},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e16",
    campus: "campus2",
    code: "E16",
    latitude: 37.544485,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 62.8906},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e17",
    campus: "campus2",
    code: "E17",
    latitude: 37.54452,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 66.6016},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e18",
    campus: "campus2",
    code: "E18",
    latitude: 37.544555,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 70.3027},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e19",
    campus: "campus2",
    code: "E19",
    latitude: 37.54459,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 74.0332},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e20",
    campus: "campus2",
    code: "E20",
    latitude: 37.544625,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 77.7734},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
];

export const booths: Booth[] = [
  {
    id: "json-1-day1-a01",
    locationId: "a01",
    date: "day1",
    name: "SID",
    category: "굿즈, 체험",
    description: "120주년 기념 키링 판매 및 럭키드로우 진행",
    menu: ["120주년 기념 키링 1개 8,000원 / 2개 15,000원 / 3개 세트 20,000원"],
    events: ["럭키드로우 1회 1,000원"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQ7d3zmtFN/" },
  },
  {
    id: "json-1-day2-a01",
    locationId: "a01",
    date: "day2",
    name: "SID",
    category: "굿즈, 체험",
    description: "120주년 기념 키링 판매 및 럭키드로우 진행",
    menu: ["120주년 기념 키링 1개 8,000원 / 2개 15,000원 / 3개 세트 20,000원"],
    events: ["럭키드로우 1회 1,000원"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQ7d3zmtFN/" },
  },
  {
    id: "json-2-day1-a02",
    locationId: "a02",
    date: "day1",
    name: "설화연",
    category: "굿즈, 체험",
    description: "픽셀 키캡 키링 만들기 체험 및 굿즈 판매",
    menu: ["2구 키캡 키링 3,500원 (2개 구매 시 6,500원)"],
    events: [
      "인스타그램 구매 인증샷 스토리 태그 시 추첨을 통해 올리브영 5,000원권 기프티콘 증정",
    ],
    operatingHours: "9월 16일 10:00 ~ 16:00, 9월 17일 10:00 ~ 13:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQXk7Smhbc/" },
  },
  {
    id: "json-2-day2-a02",
    locationId: "a02",
    date: "day2",
    name: "설화연",
    category: "굿즈, 체험",
    description: "픽셀 키캡 키링 만들기 체험 및 굿즈 판매",
    menu: ["2구 키캡 키링 3,500원 (2개 구매 시 6,500원)"],
    events: [
      "인스타그램 구매 인증샷 스토리 태그 시 추첨을 통해 올리브영 5,000원권 기프티콘 증정",
    ],
    operatingHours: "9월 16일 10:00 ~ 16:00, 9월 17일 10:00 ~ 13:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQXk7Smhbc/" },
  },
  {
    id: "json-3-day1-a03",
    locationId: "a03",
    date: "day1",
    name: "AIESEC",
    category: "음식, 체험",
    description:
      "시원한 과일 화채 판매 및 SDGs 보드게임 <아이섹마블>, 해외교류 프로그램 상담",
    menu: ["시원한 과일 화채 3,500원 (할인가)"],
    events: ["<아이섹마블> 보드게임 참여 시 간식 꾸러미 증정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNgMD-AbFV/" },
  },
  {
    id: "json-3-day1-a04",
    locationId: "a04",
    date: "day1",
    name: "AIESEC",
    category: "음식, 체험",
    description:
      "시원한 과일 화채 판매 및 SDGs 보드게임 <아이섹마블>, 해외교류 프로그램 상담",
    menu: ["시원한 과일 화채 3,500원 (할인가)"],
    events: ["<아이섹마블> 보드게임 참여 시 간식 꾸러미 증정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNgMD-AbFV/" },
  },
  {
    id: "json-3-day2-a03",
    locationId: "a03",
    date: "day2",
    name: "AIESEC",
    category: "음식, 체험",
    description:
      "시원한 과일 화채 판매 및 SDGs 보드게임 <아이섹마블>, 해외교류 프로그램 상담",
    menu: ["시원한 과일 화채 3,500원 (할인가)"],
    events: ["<아이섹마블> 보드게임 참여 시 간식 꾸러미 증정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNgMD-AbFV/" },
  },
  {
    id: "json-3-day2-a04",
    locationId: "a04",
    date: "day2",
    name: "AIESEC",
    category: "음식, 체험",
    description:
      "시원한 과일 화채 판매 및 SDGs 보드게임 <아이섹마블>, 해외교류 프로그램 상담",
    menu: ["시원한 과일 화채 3,500원 (할인가)"],
    events: ["<아이섹마블> 보드게임 참여 시 간식 꾸러미 증정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNgMD-AbFV/" },
  },
  {
    id: "json-38-day1-a06",
    locationId: "a06",
    date: "day1",
    name: "FD’link",
    category: "음식",
    description: "청파제에서만 만날 수 있는 ‘르꼬르동 브라우니’ 판매",
    menu: ["초코", "말차", "초코 + 말차", "오레오", "프레첼", "로투스"],
    events: ["9월 16일 하루 동안 소진 시까지 판매"],
    operatingHours: "9월 16일(수) 10:00 ~ 소진 시",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418155091" },
  },
  {
    id: "json-4-day1-a07",
    locationId: "a07",
    date: "day1",
    name: "숙나래",
    category: "음식, 굿즈",
    description: "마스코트 수기&나래 모티브 에이드 판매 및 동화책/굿즈 소개",
    menu: ["수기(레모네이드) 2,000원", "나래(블루레몬네이드) 2,000원"],
    events: ["개인 텀블러 지참 시 200원 할인"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQHgQEmiYA/" },
  },
  {
    id: "json-4-day1-a08",
    locationId: "a08",
    date: "day1",
    name: "숙나래",
    category: "음식, 굿즈",
    description: "마스코트 수기&나래 모티브 에이드 판매 및 동화책/굿즈 소개",
    menu: ["수기(레모네이드) 2,000원", "나래(블루레몬네이드) 2,000원"],
    events: ["개인 텀블러 지참 시 200원 할인"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQHgQEmiYA/" },
  },
  {
    id: "json-5-day1-a09",
    locationId: "a09",
    date: "day1",
    name: "S.O.F",
    category: "체험",
    description: "가족을 향한 마음을 담은 볼펜 만들기 및 가족 문자 이벤트",
    menu: ["참가비 3,500원"],
    events: [
      "볼펜 완성 또는 문자 인증 시 달콤한 간식 증정 (볼펜 + 섭서 + 간식 + 힐링 4종 세트)",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418152624" },
  },
  {
    id: "json-5-day1-a10",
    locationId: "a10",
    date: "day1",
    name: "S.O.F",
    category: "체험",
    description: "가족을 향한 마음을 담은 볼펜 만들기 및 가족 문자 이벤트",
    menu: ["참가비 3,500원"],
    events: [
      "볼펜 완성 또는 문자 인증 시 달콤한 간식 증정 (볼펜 + 섭서 + 간식 + 힐링 4종 세트)",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418152624" },
  },
  {
    id: "json-6-day1-a13",
    locationId: "a13",
    date: "day1",
    name: "데스티니",
    category: "굿즈, 음식, 체험",
    description:
      "페스티벌 굿즈 판매 및 무알콜 음료와 스낵 판매, 락 페스티벌 콘셉트 부스",
    menu: [
      "키링 1,500원",
      "핀뱃지 개당 2,000원 / 세트 5,500원",
      "스티커 3,000원",
      "나쵸 3,500원",
      "셜리 템플 3,000원",
      "블루 라군 3,000원",
    ],
    events: [
      "SNS 팔로우 시 페스티벌 팔찌 및 간식 증정",
      "공연 중 행운의 번호 추첨 경품 증정",
      "스토리에 부스/공연 태그 시 하이디라오 기프티콘 추첨 증정",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTLCxMkQnT/" },
  },
  {
    id: "json-6-day1-a14",
    locationId: "a14",
    date: "day1",
    name: "데스티니",
    category: "굿즈, 음식, 체험",
    description:
      "페스티벌 굿즈 판매 및 무알콜 음료와 스낵 판매, 락 페스티벌 콘셉트 부스",
    menu: [
      "키링 1,500원",
      "핀뱃지 개당 2,000원 / 세트 5,500원",
      "스티커 3,000원",
      "나쵸 3,500원",
      "셜리 템플 3,000원",
      "블루 라군 3,000원",
    ],
    events: [
      "SNS 팔로우 시 페스티벌 팔찌 및 간식 증정",
      "공연 중 행운의 번호 추첨 경품 증정",
      "스토리에 부스/공연 태그 시 하이디라오 기프티콘 추첨 증정",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTLCxMkQnT/" },
  },
  {
    id: "json-39-day1-a11",
    locationId: "a11",
    date: "day1",
    name: "ESCA",
    category: "굿즈, 체험",
    description:
      "중앙만화동아리 ESCA의 페이스페인팅, 굿즈 판매, 랜덤박스, ESCA쿠지 부스",
    menu: [
      "페이스페인팅 2,000원 (2개 이상 시 500원 할인)",
      "핀뱃지 각 800원 / 5개 세트 3,000원",
      "스티커 각 800원 / 6장 세트 3,800원",
      "떡메모지 각 1,200원",
      "랜덤박스 2,000원",
      "ESCA쿠지 2,000원",
    ],
    events: ["페이스페인팅 진행", "랜덤박스 및 ESCA쿠지 이벤트 진행"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418181753" },
  },
  {
    id: "json-39-day1-a12",
    locationId: "a12",
    date: "day1",
    name: "ESCA",
    category: "굿즈, 체험",
    description:
      "중앙만화동아리 ESCA의 페이스페인팅, 굿즈 판매, 랜덤박스, ESCA쿠지 부스",
    menu: [
      "페이스페인팅 2,000원 (2개 이상 시 500원 할인)",
      "핀뱃지 각 800원 / 5개 세트 3,000원",
      "스티커 각 800원 / 6장 세트 3,800원",
      "떡메모지 각 1,200원",
      "랜덤박스 2,000원",
      "ESCA쿠지 2,000원",
    ],
    events: ["페이스페인팅 진행", "랜덤박스 및 ESCA쿠지 이벤트 진행"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418181753" },
  },
  {
    id: "json-6-day2-a11",
    locationId: "a11",
    date: "day2",
    name: "데스티니",
    category: "굿즈, 음식, 체험",
    description:
      "페스티벌 굿즈 판매 및 무알콜 음료와 스낵 판매, 락 페스티벌 콘셉트 부스",
    menu: [
      "키링 1,500원",
      "핀뱃지 개당 2,000원 / 세트 5,500원",
      "스티커 3,000원",
      "나쵸 3,500원",
      "셜리 템플 3,000원",
      "블루 라군 3,000원",
    ],
    events: [
      "SNS 팔로우 시 페스티벌 팔찌 및 간식 증정",
      "공연 중 행운의 번호 추첨 경품 증정",
      "스토리에 부스/공연 태그 시 하이디라오 기프티콘 추첨 증정",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTLCxMkQnT/" },
  },
  {
    id: "json-6-day2-a12",
    locationId: "a12",
    date: "day2",
    name: "데스티니",
    category: "굿즈, 음식, 체험",
    description:
      "페스티벌 굿즈 판매 및 무알콜 음료와 스낵 판매, 락 페스티벌 콘셉트 부스",
    menu: [
      "키링 1,500원",
      "핀뱃지 개당 2,000원 / 세트 5,500원",
      "스티커 3,000원",
      "나쵸 3,500원",
      "셜리 템플 3,000원",
      "블루 라군 3,000원",
    ],
    events: [
      "SNS 팔로우 시 페스티벌 팔찌 및 간식 증정",
      "공연 중 행운의 번호 추첨 경품 증정",
      "스토리에 부스/공연 태그 시 하이디라오 기프티콘 추첨 증정",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTLCxMkQnT/" },
  },
  {
    id: "json-7-day1-b01",
    locationId: "b01",
    date: "day1",
    name: "숙미회",
    category: "굿즈, 체험",
    description:
      "중앙사진동아리 부원들이 직접 찍고 제작한 사진 굿즈 판매 및 사진 MBTI 프로그램",
    menu: ["엽서", "스티커", "안경닦이", "문진", "텐케이스", "노트", "키링"],
    events: ["SNS 홍보 엽서", "사진 MBTI"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSsac1CWIz/" },
  },
  {
    id: "json-7-day1-b02",
    locationId: "b02",
    date: "day1",
    name: "숙미회",
    category: "굿즈, 체험",
    description:
      "중앙사진동아리 부원들이 직접 찍고 제작한 사진 굿즈 판매 및 사진 MBTI 프로그램",
    menu: ["엽서", "스티커", "안경닦이", "문진", "텐케이스", "노트", "키링"],
    events: ["SNS 홍보 엽서", "사진 MBTI"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSsac1CWIz/" },
  },
  {
    id: "json-7-day2-b01",
    locationId: "b01",
    date: "day2",
    name: "숙미회",
    category: "굿즈, 체험",
    description:
      "중앙사진동아리 부원들이 직접 찍고 제작한 사진 굿즈 판매 및 사진 MBTI 프로그램",
    menu: ["엽서", "스티커", "안경닦이", "문진", "텐케이스", "노트", "키링"],
    events: ["SNS 홍보 엽서", "사진 MBTI"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSsac1CWIz/" },
  },
  {
    id: "json-7-day2-b02",
    locationId: "b02",
    date: "day2",
    name: "숙미회",
    category: "굿즈, 체험",
    description:
      "중앙사진동아리 부원들이 직접 찍고 제작한 사진 굿즈 판매 및 사진 MBTI 프로그램",
    menu: ["엽서", "스티커", "안경닦이", "문진", "텐케이스", "노트", "키링"],
    events: ["SNS 홍보 엽서", "사진 MBTI"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSsac1CWIz/" },
  },
  {
    id: "json-8-day1-b03",
    locationId: "b03",
    date: "day1",
    name: "숙명 옴부즈맨 블룸",
    category: "굿즈, 체험",
    description: "직접 디자인한 타투 스티커 샵 운영 및 현장 부착 서비스",
    menu: ["타투스티커 1장 3,500원"],
    events: ["인스타그램 팔로우 시 3,000원 할인, 디자인당 하루 40장 한정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTAzzBARni/" },
  },
  {
    id: "json-8-day2-b03",
    locationId: "b03",
    date: "day2",
    name: "숙명 옴부즈맨 블룸",
    category: "굿즈, 체험",
    description: "직접 디자인한 타투 스티커 샵 운영 및 현장 부착 서비스",
    menu: ["타투스티커 1장 3,500원"],
    events: ["인스타그램 팔로우 시 3,000원 할인, 디자인당 하루 40장 한정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTAzzBARni/" },
  },
  {
    id: "json-9-day1-b04",
    locationId: "b04",
    date: "day1",
    name: "글마실",
    category: "굿즈, 체험",
    description:
      "여름문집 <우담바라의 투시도> 선예약 및 굿즈 판매, 운세 뽑기 체험 (<글락왕생>)",
    menu: [
      "미니 인터뷰집 4,000원",
      "스티커 세트(2장) 1,500원",
      "운세 뽑기 500원",
    ],
    events: [
      "인스타그램 팔로우 시 운세 뽑기 1회 무료",
      "이야기 포스트잇 작성 후 인스타 업로드 시 간식 증정",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNxKAUk5ox/" },
  },
  {
    id: "json-10-day1-b05",
    locationId: "b05",
    date: "day1",
    name: "숙명통신원",
    category: "굿즈",
    description:
      "개강 스트레스를 날려줄 스티커 팩 판매 및 팔로우 이벤트 ('숙통 사무소')",
    menu: ["스티커 A6 사이즈/칼선 개당 2,500원"],
    events: [
      "숙명여대 및 눈송이 인스타그램 계정 모두 팔로우 시 눈송이 굿즈 증정",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418160047" },
  },
  {
    id: "json-10-day1-b06",
    locationId: "b06",
    date: "day1",
    name: "숙명통신원",
    category: "굿즈",
    description:
      "개강 스트레스를 날려줄 스티커 팩 판매 및 팔로우 이벤트 ('숙통 사무소')",
    menu: ["스티커 A6 사이즈/칼선 개당 2,500원"],
    events: [
      "숙명여대 및 눈송이 인스타그램 계정 모두 팔로우 시 눈송이 굿즈 증정",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418160047" },
  },
  {
    id: "json-11-day2-a06",
    locationId: "a06",
    date: "day2",
    name: "스노로즈",
    category: "굿즈, 체험",
    description: "조랭이떡 로고 꾸미기 및 한정 굿즈 현장 수령·판매 부스",
    menu: ["티셔츠 18,000원", "반다나 5,500원", "타투스티커 4,400원"],
    events: [
      "조랭이떡 꾸미기 참여 후 학생증 확인 시 포인트 5P 지급",
      "인스타 스토리 인증 시 20P, 스노로즈 웹 게시판 인증 시 20P 지급",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQMQYPCToY/" },
  },
  {
    id: "json-12-day2-a07",
    locationId: "a07",
    date: "day2",
    name: "프랑스언어문화학과 학생회 '더불어'",
    category: "굿즈, 체험",
    description: "'슬랑이 만들기' 체험 부스",
    menu: [
      "클리어 슬랑이 3,000원",
      "버터슬랑이/파츠 추가 각 +1,000원",
      "프랑이 3,000원 (프언문 학생은 1,000원 할인)",
    ],
    events: ["프언문 학생 할인"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQdVV1EQ5-/" },
  },
  {
    id: "json-12-day2-a08",
    locationId: "a08",
    date: "day2",
    name: "프랑스언어문화학과 학생회 '더불어'",
    category: "굿즈, 체험",
    description: "'슬랑이 만들기' 체험 부스",
    menu: [
      "클리어 슬랑이 3,000원",
      "버터슬랑이/파츠 추가 각 +1,000원",
      "프랑이 3,000원 (프언문 학생은 1,000원 할인)",
    ],
    events: ["프언문 학생 할인"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQdVV1EQ5-/" },
  },
  {
    id: "json-13-day2-a09",
    locationId: "a09",
    date: "day2",
    name: "숙명유도부",
    category: "굿즈, 체험",
    description:
      "유도력(악력, 지구력, 순발력) 측정 체험 및 유도 테마 굿즈 판매",
    menu: [
      "유도 스티커팩 3,000원",
      "아크릴 키링 각 1,500원 / 3,000원",
      "유도 파우치 5,000원",
      "키캡 키링 총 8,500원",
    ],
    events: [
      "유도력 측정 종목별 일정 점수 넘긴 유도력 충만 송이들에게 비밀 선물 증정",
      "참가만 해도 기본 선물 증정",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418177611" },
  },
  {
    id: "json-14-day1-c01",
    locationId: "c01",
    date: "day1",
    name: "경영학술부",
    category: "음식, 굿즈, 체험",
    description: "미니 마카롱 우유 말먹 및 행운의 거북이 파츠 부스",
    menu: ["미니 마카롱 우유 말먹 세트 4,000원", "행운의 거북이 파츠 500원"],
    events: [
      "원하는 거북이 파츠 선택 시 휴대폰 케이스 등 원하는 곳에 즉석 부착 서비스",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTmyUhmHhK/" },
  },
  {
    id: "json-14-day1-c02",
    locationId: "c02",
    date: "day1",
    name: "경영학술부",
    category: "음식, 굿즈, 체험",
    description: "미니 마카롱 우유 말먹 및 행운의 거북이 파츠 부스",
    menu: ["미니 마카롱 우유 말먹 세트 4,000원", "행운의 거북이 파츠 500원"],
    events: [
      "원하는 거북이 파츠 선택 시 휴대폰 케이스 등 원하는 곳에 즉석 부착 서비스",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTmyUhmHhK/" },
  },
  {
    id: "json-14-day2-c01",
    locationId: "c01",
    date: "day2",
    name: "경영학술부",
    category: "음식, 굿즈, 체험",
    description: "미니 마카롱 우유 말먹 및 행운의 거북이 파츠 부스",
    menu: ["미니 마카롱 우유 말먹 세트 4,000원", "행운의 거북이 파츠 500원"],
    events: [
      "원하는 거북이 파츠 선택 시 휴대폰 케이스 등 원하는 곳에 즉석 부착 서비스",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTmyUhmHhK/" },
  },
  {
    id: "json-14-day2-c02",
    locationId: "c02",
    date: "day2",
    name: "경영학술부",
    category: "음식, 굿즈, 체험",
    description: "미니 마카롱 우유 말먹 및 행운의 거북이 파츠 부스",
    menu: ["미니 마카롱 우유 말먹 세트 4,000원", "행운의 거북이 파츠 500원"],
    events: [
      "원하는 거북이 파츠 선택 시 휴대폰 케이스 등 원하는 곳에 즉석 부착 서비스",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTmyUhmHhK/" },
  },
  {
    id: "json-15-day1-c03",
    locationId: "c03",
    date: "day1",
    name: "금속학회 DOT",
    category: "굿즈, 체험",
    description: "귀여운 키링 판매 및 100% 당첨 럭키드로우",
    menu: ["현장 확인"],
    events: [
      "굿즈 구매 시 간식 증정",
      "꽝 없는 100% 당첨 '용과 럭키드로우' (1등 배달의민족 20,000원 상품권)",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목)",
    promoLinks: { everytime: "https://everytime.kr/367421/v/417884789" },
  },
  {
    id: "json-15-day1-c04",
    locationId: "c04",
    date: "day1",
    name: "금속학회 DOT",
    category: "굿즈, 체험",
    description: "귀여운 키링 판매 및 100% 당첨 럭키드로우",
    menu: ["현장 확인"],
    events: [
      "굿즈 구매 시 간식 증정",
      "꽝 없는 100% 당첨 '용과 럭키드로우' (1등 배달의민족 20,000원 상품권)",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목)",
    promoLinks: { everytime: "https://everytime.kr/367421/v/417884789" },
  },
  {
    id: "json-15-day2-c03",
    locationId: "c03",
    date: "day2",
    name: "공예과 금속학회 DOT",
    category: "굿즈, 체험",
    description:
      "주얼리 키링과 오브제 등 굿즈를 판매하고 럭키드로우를 진행하는 부스",
    menu: [
      "주얼리, 키링, 오브제, 장식 소품",
      "럭키드로우 상품권, 커피 상품권, 자체제작 키링, 스티커, 소정의 간식",
    ],
    events: ["럭키드로우 1,000원"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/417884789" },
  },
  {
    id: "json-15-day2-c04",
    locationId: "c04",
    date: "day2",
    name: "공예과 금속학회 DOT",
    category: "굿즈, 체험",
    description:
      "주얼리 키링과 오브제 등 굿즈를 판매하고 럭키드로우를 진행하는 부스",
    menu: [
      "주얼리, 키링, 오브제, 장식 소품",
      "럭키드로우 상품권, 커피 상품권, 자체제작 키링, 스티커, 소정의 간식",
    ],
    events: ["럭키드로우 1,000원"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/417884789" },
  },
  {
    id: "json-16-day1-c05",
    locationId: "c05",
    date: "day1",
    name: "SCSM",
    category: "굿즈, 체험",
    description: "바다 컨셉의 키링·스티커 판매 및 물고기 낚시 게임",
    menu: [
      "킥판 키링 3,000원",
      "해양생물 키링 1,000 ~ 1,500원",
      "스티커 3종 500 ~ 1,000원",
      "낚시 게임 1회 1,000원",
    ],
    events: [
      "낚시 게임 참여 후 물고기에 숨겨진 커피/편의점 기프티콘 및 SCSM 굿즈 등 상품 수령",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 20:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdStlPcmnb_/" },
  },
  {
    id: "json-16-day1-c06",
    locationId: "c06",
    date: "day1",
    name: "SCSM",
    category: "굿즈, 체험",
    description: "바다 컨셉의 키링·스티커 판매 및 물고기 낚시 게임",
    menu: [
      "킥판 키링 3,000원",
      "해양생물 키링 1,000 ~ 1,500원",
      "스티커 3종 500 ~ 1,000원",
      "낚시 게임 1회 1,000원",
    ],
    events: [
      "낚시 게임 참여 후 물고기에 숨겨진 커피/편의점 기프티콘 및 SCSM 굿즈 등 상품 수령",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 20:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdStlPcmnb_/" },
  },
  {
    id: "json-16-day2-c05",
    locationId: "c05",
    date: "day2",
    name: "교육방송국 SBS",
    category: "음식, 홍보",
    description:
      "팝콘, 나초, 레몬에이드와 함께 영화 같은 청춘의 순간을 기록하는 교육방송국 SBS 부스",
    menu: [
      "오리지널 후추 팝콘 3,500원",
      "오리지널 나초 + 치즈소스 3,500원",
      "레몬에이드 3,000원",
    ],
    events: ["SNS 사탕"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418219597" },
  },
  {
    id: "json-16-day2-c06",
    locationId: "c06",
    date: "day2",
    name: "교육방송국 SBS",
    category: "음식, 홍보",
    description:
      "팝콘, 나초, 레몬에이드와 함께 영화 같은 청춘의 순간을 기록하는 교육방송국 SBS 부스",
    menu: [
      "오리지널 후추 팝콘 3,500원",
      "오리지널 나초 + 치즈소스 3,500원",
      "레몬에이드 3,000원",
    ],
    events: ["SNS 사탕"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418219597" },
  },
  {
    id: "json-17-day1-c07",
    locationId: "c07",
    date: "day1",
    name: "UNSA",
    category: "굿즈, 체험",
    description: "'바다를 품은 키링' - 나만의 지퍼백 키링 DIY 체험",
    menu: ["지퍼백 키링 3,000원", "행운의 거북이 부착 500원"],
    events: ["키링 제작 시 행운의 거북이 부착 서비스 제공"],
    operatingHours: "9월 16일(수) 10:00 ~ 17:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNxjYyptJH/" },
  },
  {
    id: "json-17-day1-c08",
    locationId: "c08",
    date: "day1",
    name: "UNSA",
    category: "굿즈, 체험",
    description: "'바다를 품은 키링' - 나만의 지퍼백 키링 DIY 체험",
    menu: ["지퍼백 키링 3,000원", "행운의 거북이 부착 500원"],
    events: ["키링 제작 시 행운의 거북이 부착 서비스 제공"],
    operatingHours: "9월 16일(수) 10:00 ~ 17:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdNxjYyptJH/" },
  },
  {
    id: "json-17-day2-c07",
    locationId: "c07",
    date: "day2",
    name: "배슛켓볼",
    category: "음식, 굿즈",
    description:
      "식혜와 미숫가루를 판매하고 왁뿌볼을 판매하는 부스",
    menu: ["식혜 2,500원", "미숫가루 2,500원", "농구공 왁뿌볼 4,000원"],
    events: [],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418200060" },
  },
  {
    id: "json-17-day2-c08",
    locationId: "c08",
    date: "day2",
    name: "MAX",
    category: "음식",
    description:
      "뿌링 나초와 디핑 소스를 즐기고, 원하는 간식에 뿌링 가루를 추가할 수 있는 부스",
    menu: ["뿌링 나초 - 살사 소스 / 체다 치즈 딥 / 갈릭 디핑"],
    events: [
      "내맘대로 뿌링 추가 - 타 부스 및 푸드트럭에서 구매한 간식 또는 원하는 과자를 지참하면 뿌링 가루 증정",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {},
  },
  {
    id: "json-18-day1-c09",
    locationId: "c09",
    date: "day1",
    name: "종강대책위원회 - 청명",
    category: "굿즈, 체험",
    description:
      "시험기간/스트레스 해소용 메모지, 슬랑이, 긴급 탈출 키 판매 및 다트 게임 부스",
    menu: [
      "송이의 시험기간 3종 처방전(메모지) 2,500원",
      "과바텀 크런치 슬랑이 7,000원",
      "긴급 탈출 키(3종 중 택 1) 개당 3,500원",
      "다트 게임('다트: 아이고 종강이야~') 2,000원 (공 3개)",
    ],
    events: [
      "다트 게임 점수에 따른 할인권 및 간식 증정",
      "1단계 성공자 중 추첨을 통해 올리브영 1만원권 증정",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 18:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTR-49lOJ0/" },
  },
  {
    id: "json-18-day1-c10",
    locationId: "c10",
    date: "day1",
    name: "종강대책위원회 - 청명",
    category: "굿즈, 체험",
    description:
      "시험기간/스트레스 해소용 메모지, 슬랑이, 긴급 탈출 키 판매 및 다트 게임 부스",
    menu: [
      "송이의 시험기간 3종 처방전(메모지) 2,500원",
      "과바텀 크런치 슬랑이 7,000원",
      "긴급 탈출 키(3종 중 택 1) 개당 3,500원",
      "다트 게임('다트: 아이고 종강이야~') 2,000원 (공 3개)",
    ],
    events: [
      "다트 게임 점수에 따른 할인권 및 간식 증정",
      "1단계 성공자 중 추첨을 통해 올리브영 1만원권 증정",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 18:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTR-49lOJ0/" },
  },
  {
    id: "json-18-day2-c09",
    locationId: "c09",
    date: "day2",
    name: "번뇌상사",
    category: "굿즈",
    description:
      "오버핏 티셔츠, 쿼키 티셔츠, 에코백, 천포스터 등 다양한 굿즈 판매",
    menu: [
      "오버핏 티셔츠 4종",
      "쿼키 티셔츠 2종",
      "에코백 4종",
      "천포스터 4종",
      "스티커",
      "컵",
      "엽서 4종",
      "말랑이 3종",
      "랜덤 피규어 4종",
      "키링 6종",
      "염주 4종",
      "인센스 홀더 2종 등",
    ],
    events: [],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {},
  },
  {
    id: "json-18-day2-c10",
    locationId: "c10",
    date: "day2",
    name: "번뇌상사",
    category: "굿즈",
    description:
      "오버핏 티셔츠, 쿼키 티셔츠, 에코백, 천포스터 등 다양한 굿즈 판매",
    menu: [
      "오버핏 티셔츠 4종",
      "쿼키 티셔츠 2종",
      "에코백 4종",
      "천포스터 4종",
      "스티커",
      "컵",
      "엽서 4종",
      "말랑이 3종",
      "랜덤 피규어 4종",
      "키링 6종",
      "염주 4종",
      "인센스 홀더 2종 등",
    ],
    events: [],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {},
  },
  {
    id: "json-19-day1-c11",
    locationId: "c11",
    date: "day1",
    name: "경영학부 학회 향영",
    category: "굿즈, 체험",
    description: "고무피부터 파츠까지 직접 고르는 나만의 말랑이 만들기 부스",
    menu: [
      "고무피(곰발바닥/큰 원/작은 원/하트) 5,000원 또는 6,000원",
      "파츠(눈송이, 거북이 등 약 20종) 800 ~ 1,500원",
    ],
    events: ["취향에 맞는 재료를 골라 커스텀 말랑이 제작"],
    operatingHours: "9월 16일(수) 10:00 ~ 20:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418157126" },
  },
  {
    id: "json-19-day1-c12",
    locationId: "c12",
    date: "day1",
    name: "경영학부 학회 향영",
    category: "굿즈, 체험",
    description: "고무피부터 파츠까지 직접 고르는 나만의 말랑이 만들기 부스",
    menu: [
      "고무피(곰발바닥/큰 원/작은 원/하트) 5,000원 또는 6,000원",
      "파츠(눈송이, 거북이 등 약 20종) 800 ~ 1,500원",
    ],
    events: ["취향에 맞는 재료를 골라 커스텀 말랑이 제작"],
    operatingHours: "9월 16일(수) 10:00 ~ 20:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418157126" },
  },
  {
    id: "json-19-day2-c11",
    locationId: "c11",
    date: "day2",
    name: "한입포옹",
    category: "음식, 체험",
    description:
      "직접 구워낸 휘낭시에와 동물 쿠키를 만날 수 있는 부스",
    menu: [
      "오리지널 휘낭시에 2,500원",
      "솔티초코 휘낭시에 2,800원",
      "츄러스 휘낭시에 2,800원",
      "얼그레이 휘낭시에 2,800원",
      "핫도그 휘낭시에 3,200원",
      "쿠키세트 체험 4,000원"
    ],
    events: [
      "휘낭시에 1개 구매 시 - 쿠키세트 + 휘낭시에 전체 500원 할인",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418221298" },
  },
  {
    id: "json-19-day2-c12",
    locationId: "c12",
    date: "day2",
    name: "한입포옹",
    category: "음식, 체험",
    description:
      "직접 구워낸 휘낭시에와 동물 쿠키를 만날 수 있는 부스",
    menu: [
      "오리지널 휘낭시에 2,500원",
      "솔티초코 휘낭시에 2,800원",
      "츄러스 휘낭시에 2,800원",
      "얼그레이 휘낭시에 2,800원",
      "핫도그 휘낭시에 3,200원",
      "쿠키세트 체험 4,000원"
    ],
    events: [
      "휘낭시에 1개 구매 시 - 쿠키세트 + 휘낭시에 전체 500원 할인",],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418221298" },
  },
  // 9월 17일 밤 부스 — C구역 최신 배치 기준.
  {
    id: "json-night-day2-c09",
    locationId: "c09",
    date: "day2",
    session: "night",
    name: "번뇌상사",
    category: "굿즈",
    description:
      "오버핏 티셔츠, 쿼키 티셔츠, 에코백, 천포스터 등 다양한 굿즈 판매",
    menu: [
      "오버핏 티셔츠 4종",
      "쿼키 티셔츠 2종",
      "에코백 4종",
      "천포스터 4종",
      "스티커",
      "컵",
      "엽서 4종",
      "말랑이 3종",
      "랜덤 피규어 4종",
      "키링 6종",
      "염주 4종",
      "인센스 홀더 2종 등",
    ],
    events: [],
    operatingHours: "9월 17일(목) 16:30 ~ 20:00",
    promoLinks: {},
  },
  {
    id: "json-night-day2-c10",
    locationId: "c10",
    date: "day2",
    session: "night",
    name: "번뇌상사",
    category: "굿즈",
    description:
      "오버핏 티셔츠, 쿼키 티셔츠, 에코백, 천포스터 등 다양한 굿즈 판매",
    menu: [
      "오버핏 티셔츠 4종",
      "쿼키 티셔츠 2종",
      "에코백 4종",
      "천포스터 4종",
      "스티커",
      "컵",
      "엽서 4종",
      "말랑이 3종",
      "랜덤 피규어 4종",
      "키링 6종",
      "염주 4종",
      "인센스 홀더 2종 등",
    ],
    events: [],
    operatingHours: "9월 17일(목) 16:30 ~ 20:00",
    promoLinks: {},
  },
  {
    id: "json-night-day2-c11",
    locationId: "c11",
    date: "day2",
    session: "night",
    name: "구름바다햇살",
    category: "굿즈",
    description:
      "직접 찍은 사진으로 제작한 엽서와 폰 배경화면 세트를 판매하는 부스",
    menu: [
      "엽서 - 각 1,500원",
      "엽서 5장 - 6,000원",
      "엽서 10장 - 10,000원",
      "폰 배경화면 세트 - 각 500원",
    ],
    events: [
      "세 가지 주제와 특별 엽서로 구성된 엽서 판매",
      "세 가지 주제에 맞는 폰 배경화면 세트 판매",
      "폰 배경화면은 QR코드/카카오톡 1:1 오픈채팅방으로 파일 전송",
      "구매하지 않아도 즐길 수 있는 환영 선물 제공",
    ],
    operatingHours: "9월 17일(목) 16:30 ~ 20:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418230157" },
  },
  {
    id: "json-night-day2-c12",
    locationId: "c12",
    date: "day2",
    session: "night",
    name: "구름바다햇살",
    category: "굿즈",
    description:
      "직접 찍은 사진으로 제작한 엽서와 폰 배경화면 세트를 판매하는 부스",
    menu: [
      "엽서 - 각 1,500원",
      "엽서 5장 - 6,000원",
      "엽서 10장 - 10,000원",
      "폰 배경화면 세트 - 각 500원",
    ],
    events: [
      "세 가지 주제와 특별 엽서로 구성된 엽서 판매",
      "세 가지 주제에 맞는 폰 배경화면 세트 판매",
      "폰 배경화면은 QR코드/카카오톡 1:1 오픈채팅방으로 파일 전송",
      "구매하지 않아도 즐길 수 있는 환영 선물 제공",
    ],
    operatingHours: "9월 17일(목) 16:30 ~ 20:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418230157" },
  },
  {
    id: "json-20-day1-d01",
    locationId: "d01",
    date: "day1",
    name: "SAI",
    category: "굿즈, 체험",
    description: "매듭 참, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 이벤트 참여"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQcm9nneTL/" },
  },
  {
    id: "json-20-day1-d02",
    locationId: "d02",
    date: "day1",
    name: "SAI",
    category: "굿즈, 체험",
    description: "매듭 참, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 이벤트 참여"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQcm9nneTL/" },
  },
  {
    id: "json-20-day2-d01",
    locationId: "d01",
    date: "day2",
    name: "SAI",
    category: "굿즈, 체험",
    description: "매듭 참, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 이벤트 참여"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQcm9nneTL/" },
  },
  {
    id: "json-20-day2-d02",
    locationId: "d02",
    date: "day2",
    name: "SAI",
    category: "굿즈, 체험",
    description: "매듭 참, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 이벤트 참여"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQcm9nneTL/" },
  },
  {
    id: "json-21-day1-d03",
    locationId: "d03",
    date: "day1",
    name: "SAA",
    category: "굿즈, 체험",
    description: "'구슬다락방' - 가을 감성을 담은 팔찌 판매 및 럭키드로우",
    menu: ["오색빛 구슬 팔찌 4,000원", "무화과 끈 팔찌 4,000원"],
    events: ["한정 수량 럭키드로우 이벤트 진행"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQh0q3k8aK/" },
  },
  {
    id: "json-21-day2-d03",
    locationId: "d03",
    date: "day2",
    name: "SAA",
    category: "굿즈, 체험",
    description: "'구슬다락방' - 가을 감성을 담은 팔찌 판매 및 럭키드로우",
    menu: ["오색빛 구슬 팔찌 4,000원", "무화과 끈 팔찌 4,000원"],
    events: ["한정 수량 럭키드로우 이벤트 진행"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQh0q3k8aK/" },
  },
  {
    id: "json-22-day1-d04",
    locationId: "d04",
    date: "day1",
    name: "숙불회",
    category: "체험",
    description:
      "향기와 명상을 통한 일상의 여유 제공 및 무료 체험 부스 ('사티클럽')",
    menu: ["무료 체험"],
    events: ["매일 선착순 80명 숙불회 굿즈 스티커 증정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418164193" },
  },
  {
    id: "json-22-day2-d04",
    locationId: "d04",
    date: "day2",
    name: "숙불회",
    category: "체험",
    description:
      "향기와 명상을 통한 일상의 여유 제공 및 무료 체험 부스 ('사티클럽')",
    menu: ["무료 체험"],
    events: ["매일 선착순 80명 숙불회 굿즈 스티커 증정"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418164193" },
  },
  {
    id: "json-23-day1-d05",
    locationId: "d05",
    date: "day1",
    name: "숙파이크",
    category: "굿즈, 체험",
    description:
      "순발력 게임 및 서전트 점프 측정 체험과 배구·동물 테마 굿즈 판매",
    menu: [
      "고양이 키링(4종) 3,500원",
      "배구공·네잎클로버·토마토 키링 3,000 ~ 4,000원",
      "동물 키링(5종) 5,000원",
    ],
    events: ["순발력 게임 및 서전트 점프 측정 참여와 상품 증정"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSnKTWieVz/" },
  },
  {
    id: "json-23-day1-d06",
    locationId: "d06",
    date: "day1",
    name: "숙파이크",
    category: "굿즈, 체험",
    description:
      "순발력 게임 및 서전트 점프 측정 체험과 배구·동물 테마 굿즈 판매",
    menu: [
      "고양이 키링(4종) 3,500원",
      "배구공·네잎클로버·토마토 키링 3,000 ~ 4,000원",
      "동물 키링(5종) 5,000원",
    ],
    events: ["순발력 게임 및 서전트 점프 측정 참여와 상품 증정"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSnKTWieVz/" },
  },
  {
    id: "json-24-day1-d07",
    locationId: "d07",
    date: "day1",
    name: "육군ROTC",
    category: "체험, 상담",
    description: "후반기 모집 관련 상담 부스 운영",
    events: [
      "온라인 지원자 대상 카페 본솔 쿠폰, 보조배터리, 로카티, 칫솔세트, 물티슈 증정",
      "인성 검사 완료 시 곰돌이 키링 증정",
    ],
    operatingHours:
      "9월 16일(수) ~ 9월 17일(목) 11:00 ~ 15:00 (상황에 따라 변동 가능)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTcq4XD5Eb/" },
  },
  {
    id: "json-24-day1-d08",
    locationId: "d08",
    date: "day1",
    name: "육군ROTC",
    category: "체험, 상담",
    description: "후반기 모집 관련 상담 부스 운영",
    events: [
      "온라인 지원자 대상 카페 본솔 쿠폰, 보조배터리, 로카티, 칫솔세트, 물티슈 증정",
      "인성 검사 완료 시 곰돌이 키링 증정",
    ],
    operatingHours:
      "9월 16일(수) ~ 9월 17일(목) 11:00 ~ 15:00 (상황에 따라 변동 가능)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTcq4XD5Eb/" },
  },
  {
    id: "json-24-day2-d07",
    locationId: "d07",
    date: "day2",
    name: "육군ROTC",
    category: "체험, 상담",
    description: "후반기 모집 관련 상담 부스 운영",
    events: [
      "온라인 지원자 대상 카페 본솔 쿠폰, 보조배터리, 로카티, 칫솔세트, 물티슈 증정",
      "인성 검사 완료 시 곰돌이 키링 증정",
    ],
    operatingHours:
      "9월 16일(수) ~ 9월 17일(목) 11:00 ~ 15:00 (상황에 따라 변동 가능)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTcq4XD5Eb/" },
  },
  {
    id: "json-24-day2-d08",
    locationId: "d08",
    date: "day2",
    name: "육군ROTC",
    category: "체험, 상담",
    description: "후반기 모집 관련 상담 부스 운영",
    events: [
      "온라인 지원자 대상 카페 본솔 쿠폰, 보조배터리, 로카티, 칫솔세트, 물티슈 증정",
      "인성 검사 완료 시 곰돌이 키링 증정",
    ],
    operatingHours:
      "9월 16일(수) ~ 9월 17일(목) 11:00 ~ 15:00 (상황에 따라 변동 가능)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTcq4XD5Eb/" },
  },
  {
    id: "json-25-day2-d05",
    locationId: "d05",
    date: "day2",
    name: "코드블루",
    category: "굿즈, 체험",
    description:
      "음악 미션 게임(<CHORD RED>)을 해결하고 시스템을 복구하는 체험 부스",
    menu: ["무료 체험 및 미션 보상"],
    events: [
      "1단계 통과: 전통 간식 꾸러미",
      "2단계 통과: 코드블루 눈송이 스티커",
      "3단계 통과: 비눗방울 + 럭키드로우 뽑기권 1장 (1등 말랑이 2개, 2등 키캡 키링 5개, 3등 자체제작 눈송이 메모지 50개)",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSq1PGEuZI/" },
  },
  {
    id: "json-25-day2-d06",
    locationId: "d06",
    date: "day2",
    name: "코드블루",
    category: "굿즈, 체험",
    description:
      "음악 미션 게임(<CHORD RED>)을 해결하고 시스템을 복구하는 체험 부스",
    menu: ["무료 체험 및 미션 보상"],
    events: [
      "1단계 통과: 전통 간식 꾸러미",
      "2단계 통과: 코드블루 눈송이 스티커",
      "3단계 통과: 비눗방울 + 럭키드로우 뽑기권 1장 (1등 말랑이 2개, 2등 키캡 키링 5개, 3등 자체제작 눈송이 메모지 50개)",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSq1PGEuZI/" },
  },
  {
    id: "direct-seollem-day1-a05",
    source: "direct",
    locationId: "a05",
    date: "day1",
    name: "중앙뮤지컬동아리 설렘",
    category: "체험",
    description:
      "뮤지컬 작품에서 영감을 받은 다양한 색상과 파츠로 나만의 슬라임을 만드는 체험 부스",
    menu: ["나만의 슬라임 만들기 체험 3,000원"],
    events: [
      "원하는 색의 슬라임을 고르고 파츠와 스티커를 취향대로 선택",
      "직접 꾸민 나만의 슬라임을 완성해 가져가기",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418224586" },
  },
  {
    id: "direct-seollem-day2-a05",
    source: "direct",
    locationId: "a05",
    date: "day2",
    name: "중앙뮤지컬동아리 설렘",
    category: "체험",
    description:
      "뮤지컬 작품에서 영감을 받은 다양한 색상과 파츠로 나만의 슬라임을 만드는 체험 부스",
    menu: ["나만의 슬라임 만들기 체험 3,000원"],
    events: [
      "원하는 색의 슬라임을 고르고 파츠와 스티커를 취향대로 선택",
      "직접 꾸민 나만의 슬라임을 완성해 가져가기",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418224586" },
  },
  {
    id: "json-26-day2-e03",
    locationId: "e03",
    date: "day2",
    name: "설미",
    category: "굿즈",
    description:
      "유화/아크릴 물감으로 그린 엽서와 직접 제작한 캐리커쳐, 페이스페인팅을 운영하는 중앙동아리 부스",
    menu: [
      "엽서 1장 1,000원",
      "엽서 6장 세트 5,000원",
      "캐리커쳐 2컷 1,500원",
      "페이스페인팅 1,000원",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418173848" },
  },
  {
    id: "json-26-day2-e04",
    locationId: "e04",
    date: "day2",
    name: "설미",
    category: "굿즈",
    description:
      "유화/아크릴 물감으로 그린 엽서와 직접 제작한 캐리커쳐, 페이스페인팅을 운영하는 중앙동아리 부스",
    menu: [
      "엽서 1장 1,000원",
      "엽서 6장 세트 5,000원",
      "캐리커쳐 2컷 1,500원",
      "페이스페인팅 1,000원",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418173848" },
  },
  {
    id: "json-27-day1-e07",
    locationId: "e07",
    date: "day1",
    name: "폴라리스",
    category: "음식",
    description: "'폴송이의 아이스크림 가게' - 밀크 아이스크림과 토핑 커스텀",
    menu: [
      "초코바삭이정식 (아이스크림 + 초코쉘 + 씨리얼 1종) 2,500원",
      "폴바삭이정식 (아이스크림 + 씨리얼 3종) 2,800원",
      "폴송이 pick (아이스크림 + 풀토핑) 3,200원",
      "개별 토핑: 씨리얼 각 300원, 초코쉘 +500원",
    ],
    operatingHours: "청파제 기간 내",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQiV0hGkIs/" },
  },
  {
    id: "json-27-day1-e08",
    locationId: "e08",
    date: "day1",
    name: "폴라리스",
    category: "음식",
    description: "'폴송이의 아이스크림 가게' - 밀크 아이스크림과 토핑 커스텀",
    menu: [
      "초코바삭이정식 (아이스크림 + 초코쉘 + 씨리얼 1종) 2,500원",
      "폴바삭이정식 (아이스크림 + 씨리얼 3종) 2,800원",
      "폴송이 pick (아이스크림 + 풀토핑) 3,200원",
      "개별 토핑: 씨리얼 각 300원, 초코쉘 +500원",
    ],
    operatingHours: "청파제 기간 내",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQiV0hGkIs/" },
  },
  {
    id: "json-27-day2-e07",
    locationId: "e07",
    date: "day2",
    name: "폴라리스",
    category: "음식",
    description: "'폴송이의 아이스크림 가게' - 밀크 아이스크림과 토핑 커스텀",
    menu: [
      "초코바삭이정식 (아이스크림 + 초코쉘 + 씨리얼 1종) 2,500원",
      "폴바삭이정식 (아이스크림 + 씨리얼 3종) 2,800원",
      "폴송이 pick (아이스크림 + 풀토핑) 3,200원",
      "개별 토핑: 씨리얼 각 300원, 초코쉘 +500원",
    ],
    operatingHours: "청파제 기간 내",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQiV0hGkIs/" },
  },
  {
    id: "json-27-day2-e08",
    locationId: "e08",
    date: "day2",
    name: "폴라리스",
    category: "음식",
    description: "'폴송이의 아이스크림 가게' - 밀크 아이스크림과 토핑 커스텀",
    menu: [
      "초코바삭이정식 (아이스크림 + 초코쉘 + 씨리얼 1종) 2,500원",
      "폴바삭이정식 (아이스크림 + 씨리얼 3종) 2,800원",
      "폴송이 pick (아이스크림 + 풀토핑) 3,200원",
      "개별 토핑: 씨리얼 각 300원, 초코쉘 +500원",
    ],
    operatingHours: "청파제 기간 내",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQiV0hGkIs/" },
  },
  {
    id: "json-28-day1-e09",
    locationId: "e09",
    date: "day1",
    name: "숙명 도자학회 아람",
    category: "굿즈",
    description: "아람 학회원들의 특색이 묻어나는 도자 작업물 판매 부스",
    menu: [
      "컵, 접시 등 식기류",
      "목걸이 등 악세서리",
      "워리스톤, 키링 등 도자 제품",
    ],
    operatingHours: "9월 16일 ~ 9월 17일 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418146665" },
  },
  {
    id: "json-28-day2-e09",
    locationId: "e09",
    date: "day2",
    name: "숙명 도자학회 아람",
    category: "굿즈",
    description: "아람 학회원들의 특색이 묻어나는 도자 작업물 판매 부스",
    menu: [
      "컵, 접시 등 식기류",
      "목걸이 등 악세서리",
      "워리스톤, 키링 등 도자 제품",
    ],
    operatingHours: "9월 16일 ~ 9월 17일 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418146665" },
  },
  {
    id: "json-29-day1-e10",
    locationId: "e10",
    date: "day1",
    name: "숙명문화봉사단",
    category: "굿즈, 체험, 이벤트",
    description:
      "[✨️황실로부터의초대✨️] 주제로 교내 박물관과 미술관을 소개하고 굿즈 판매 및 이벤트 진행",
    menu: [
      "오얏꽃 문양 스크런치 3,500원",
      "눈꽃·오얏꽃 문양 노리개 4,000원",
      "120주년 기념 키캡 9,000원",
      "숙명여대 박물관 티셔츠 15,000원",
    ],
    events: [
      "인스타그램 팔로우 또는 스토리 업로드 시 간식 증정",
      "문봉 퀴즈 이벤트 (상/하 난이도별 띠부띠부씰 및 책갈피 증정)",
      "눈송이 투어 얼리버드 신청 시 당일 간식 증정",
    ],
    operatingHours: "9월 16일(수), 9월 17일(목) 09:00 ~ 16:30",
    promoLinks: { instagram: "https://www.instagram.com/p/DdIkZfRgRZD/" },
  },
  {
    id: "json-29-day2-e10",
    locationId: "e10",
    date: "day2",
    name: "숙명문화봉사단",
    category: "굿즈, 체험, 이벤트",
    description:
      "[✨️황실로부터의초대✨️] 주제로 교내 박물관과 미술관을 소개하고 굿즈 판매 및 이벤트 진행",
    menu: [
      "오얏꽃 문양 스크런치 3,500원",
      "눈꽃·오얏꽃 문양 노리개 4,000원",
      "120주년 기념 키캡 9,000원",
      "숙명여대 박물관 티셔츠 15,000원",
    ],
    events: [
      "인스타그램 팔로우 또는 스토리 업로드 시 간식 증정",
      "문봉 퀴즈 이벤트 (상/하 난이도별 띠부띠부씰 및 책갈피 증정)",
      "눈송이 투어 얼리버드 신청 시 당일 간식 증정",
    ],
    operatingHours: "9월 16일(수), 9월 17일(목) 09:00 ~ 16:30",
    promoLinks: { instagram: "https://www.instagram.com/p/DdIkZfRgRZD/" },
  },
  {
    id: "json-30-day1-e11",
    locationId: "e11",
    date: "day1",
    name: "숙명로타랙트",
    category: "체험",
    description: "쿠키 DIY 체험 및 아동복지시설 '혜심원' 기부 부스 운영",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원 (기부 할인 혜택)"],
    events: ["나만의 쿠키 꾸미기 체험", "아동복지시설 '혜심원' 쿠키 기부 전달"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdRKHKCk8o5/" },
  },
  {
    id: "json-30-day1-e12",
    locationId: "e12",
    date: "day1",
    name: "숙명로타랙트",
    category: "체험",
    description: "쿠키 DIY 체험 및 아동복지시설 '혜심원' 기부 부스 운영",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원 (기부 할인 혜택)"],
    events: ["나만의 쿠키 꾸미기 체험", "아동복지시설 '혜심원' 쿠키 기부 전달"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdRKHKCk8o5/" },
  },
  {
    id: "json-30-day2-e11",
    locationId: "e11",
    date: "day2",
    name: "숙명로타랙트",
    category: "체험",
    description: "쿠키 DIY 체험 및 아동복지시설 '혜심원' 기부 부스 운영",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원 (기부 할인 혜택)"],
    events: ["나만의 쿠키 꾸미기 체험", "아동복지시설 '혜심원' 쿠키 기부 전달"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdRKHKCk8o5/" },
  },
  {
    id: "json-30-day2-e12",
    locationId: "e12",
    date: "day2",
    name: "숙명로타랙트",
    category: "체험",
    description: "쿠키 DIY 체험 및 아동복지시설 '혜심원' 기부 부스 운영",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원 (기부 할인 혜택)"],
    events: ["나만의 쿠키 꾸미기 체험", "아동복지시설 '혜심원' 쿠키 기부 전달"],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdRKHKCk8o5/" },
  },
  {
    id: "json-31-day2-e14",
    locationId: "e14",
    date: "day2",
    name: "스마티어",
    category: "굿즈, 체험",
    description: "'스마티어 마법소' 부스로, 독서 레벨 측정 및 마법 굿즈 판매",
    menu: ["양면 책갈피 2종", "눈송이 아크릴 키링 3종", "스티커 3종", "특전 영수증", "키링", "책갈피"],
    events: [
      "부스 참여자 전원 수료증 명함 책갈피 및 독서 레벨 스티커 3종 증정",
      "굿즈 구매 시 영수증 책갈피 특전 증정",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { instagram: "https://www.instagram.com/p/DdQHpEpEzv_/" },
  },
  {
    id: "json-32-day1-e14",
    locationId: "e14",
    date: "day1",
    name: "숙명지식봉사단",
    category: "굿즈, 체험, 기부",
    description: "'지봉키캡공방' 부스를 운영하여 나만의 커스텀 키캡 제작 체험",
    menu: ["지봉 키캡 제작 5,000원 (이벤트 참여 시 10% 할인)"],
    events: [
      "키캡 할인 및 행복 풍선 꾸미기",
      "수익금 전액 소외계층 아동 교육 여건 개선 기부",
    ],
    operatingHours: "2026년 9월 16일 수요일 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418189623" },
  },
  {
    id: "json-33-day1-e17",
    locationId: "e17",
    date: "day1",
    name: "문헌정보학과 학생회 온결",
    category: "굿즈, 체험",
    description:
      "<숙명문정도서전> - 독서 성향 테스트 및 끈갈피 만들기 체험과 굿즈 판매",
    menu: [
      "종이부채 2종 1,000원",
      "독서가 스티커 3종 세트 3,000원",
      "DIY 끈갈피 개당 6,000원",
      "끈갈피 만들기 체험비 4,000원",
    ],
    events: [
      "나만의 책 MBTI [북BTI] 테스트 및 맞춤 책갈피 증정",
      "영롱한 끈갈피 만들기 체험",
      "깜짝 나눔용 굿즈 진행",
    ],
    operatingHours: "2026년 9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418148812" },
  },
  {
    id: "json-33-day1-e18",
    locationId: "e18",
    date: "day1",
    name: "문헌정보학과 학생회 온결",
    category: "굿즈, 체험",
    description:
      "<숙명문정도서전> - 독서 성향 테스트 및 끈갈피 만들기 체험과 굿즈 판매",
    menu: [
      "종이부채 2종 1,000원",
      "독서가 스티커 3종 세트 3,000원",
      "DIY 끈갈피 개당 6,000원",
      "끈갈피 만들기 체험비 4,000원",
    ],
    events: [
      "나만의 책 MBTI [북BTI] 테스트 및 맞춤 책갈피 증정",
      "영롱한 끈갈피 만들기 체험",
      "깜짝 나눔용 굿즈 진행",
    ],
    operatingHours: "2026년 9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418148812" },
  },
  {
    id: "json-34-day2-e17",
    locationId: "e17",
    date: "day2",
    name: "왜 저 떠봐요?",
    category: "굿즈, 체험",
    description: "뜨개 및 수공예 물품 판매, 작품 전시, 행운의 뽑기",
    menu: [
      "행운의 독버섯 키링 4,500원",
      "야구공 키링 4,000원",
      "방울토마토 키링 3,000원",
      "수박 파우치 4,500원",
      "들꽃 헤어 스크런치 4,000원",
      "안아줘요 북 & 미니 파우치 13,000 ~ 18,000원",
      "물 먹는 티-코스터 2,500 ~ 3,500원",
      "뜨개-찌라시 스티커 개당 700원 / 세트 1,200원",
      "삐이따이 DIY 키트 5,000원",
    ],
    events: [
      "인스타그램 스토리 태그 시 500원 할인",
      "천 원의 행복 행운의 뽑기 (1~5등 경품 차등 지급)",
      "작품 전시",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/390063009" },
  },
  {
    id: "json-35-day2-e20",
    locationId: "e20",
    date: "day2",
    name: "자치언론 파란",
    category: "굿즈, 체험, 이벤트",
    description: "신간 <파란 14호: 용감무쌍> 및 굿즈 판매와 참여형 이벤트",
    menu: [
      "숙명사랑해 티셔츠 15,000원",
      "파도 위의 사랑 티셔츠 15,000원",
      "노트북 스티커 1,000원",
      "파란 안경닦이 4,000원",
      "타투스티커 2,500원",
      "용기를 주는 달걀 1,000원",
      "타투 스티커 부착 서비스 500원",
    ],
    events: [
      "인스타그램 팔로우/구매 인증 및 포스트잇 캠페인 참여 시 야광팔찌 증정",
      "용기를 주는 달걀 구매",
      "타투 스티커 부착 서비스",
    ],
    operatingHours: "2026년 9월 17일(목)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdSksIMk5Yy/" },
  },
  {
    id: "json-36-day2-e19",
    locationId: "e19",
    date: "day2",
    name: "뜨개송송",
    category: "굿즈, 체험",
    description:
      "뜨개 키링, 지갑, 티코스터, 책갈피 및 비즈 키링 판매 및 작품 전시",
    menu: [
      "물고기 키링 4,000원",
      "눈꽃 키링 3,500원",
      "토마토/나뭇잎 티코스터 각 6,000원",
      "토마토 키링 5,000원",
      "버섯 키링 3,500원",
      "호박 키링 5,000원",
      "지갑 6,000 ~ 6,500원",
    ],
    events: ["2,000원 꽝 없는 랜덤 뽑기 이벤트", "뜨개 작품 전시 및 포토존"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/389971133" },
  },
  {
    id: "json-37-day2-e18",
    locationId: "e18",
    date: "day2",
    name: "TUMS",
    category: "체험, 굿즈",
    description: "게임 메타버스 개발 동아리 - 개발 게임 전시 및 체험",
    menu: ["무료 참여"],
    events: [
      "동아리 개발 게임 전시",
      "현실 속 멫챠 카멜레온 피규어 찾기",
      "꽝 없는 뽑기를 통한 간식 및 눈송이 인형 경품 지급",
    ],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/367421/v/418096740" },
  },

  // 신규 상세 부스 — 9/16~9/17 공개 정보 반영
  {
    id: "json-38-day1-e05",
    locationId: "e05",
    date: "day1",
    name: "숙명 CCC",
    category: "음식",
    description: "청파제 기간 동안 눈송이 달고나를 무료로 나눠주는 부스",
    menu: ["눈송이 달고나"],
    events: [
      "동아리 소개 및 목적에 대한 설명",
      "간단한 퀴즈",
      "눈송이 달고나 무료 나눔",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTDvBup9AN/" },
  },
  {
    id: "json-38-day1-e06",
    locationId: "e06",
    date: "day1",
    name: "숙명 CCC",
    category: "음식",
    description: "청파제 기간 동안 눈송이 달고나를 무료로 나눠주는 부스",
    menu: ["눈송이 달고나"],
    events: [
      "동아리 소개 및 목적에 대한 설명",
      "간단한 퀴즈",
      "눈송이 달고나 무료 나눔",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTDvBup9AN/" },
  },
  {
    id: "json-38-day2-e05",
    locationId: "e05",
    date: "day2",
    name: "숙명 CCC",
    category: "음식",
    description: "청파제 기간 동안 눈송이 달고나를 무료로 나눠주는 부스",
    menu: ["눈송이 달고나 무료 나눔"],
    events: [
      "동아리 소개 및 목적에 대한 설명",
      "간단한 퀴즈",
      "눈송이 달고나 무료 나눔",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTDvBup9AN/" },
  },
  {
    id: "json-38-day2-e06",
    locationId: "e06",
    date: "day2",
    name: "숙명 CCC",
    category: "음식",
    description: "청파제 기간 동안 눈송이 달고나를 무료로 나눠주는 부스",
    menu: ["눈송이 달고나 무료 나눔"],
    events: [
      "동아리 소개 및 목적에 대한 설명",
      "간단한 퀴즈",
      "눈송이 달고나 무료 나눔",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목)",
    promoLinks: { instagram: "https://www.instagram.com/p/DdTDvBup9AN/" },
  },
  {
    id: "json-39-day1-e13",
    locationId: "e13",
    date: "day1",
    name: "자유전공학부 비상대책위원회",
    category: "음식, 체험",
    description:
      "축제 MBTI를 알아보고, 초콜릿을 조합해 나만의 간식컵을 완성하는 체험형 부스",
    menu: ["간식컵 & 럭키드로우 3,000원"],
    events: [
      "축제 MBTI 12문항 테스트",
      "테스트 결과에 맞는 초콜릿 4종으로 간식컵 완성",
      "간식컵 바닥의 랜덤 MBTI 스티커와 테스트 결과의 일치 알파벳 수에 따른 선착순 경품 지급",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418103530" },
  },
  {
    id: "json-39-day2-e13",
    locationId: "e13",
    date: "day2",
    name: "자유전공학부 비상대책위원회",
    category: "음식, 체험",
    description:
      "축제 상황에 맞춘 12가지 문항으로 나만의 축제 MBTI를 알아보고, 결과에 맞는 초콜릿을 조합해 나만의 간식컵을 완성하는 체험형 부스",
    menu: ["간식컵 & 럭키드로우 3,000원"],
    events: [
      "축제 MBTI 12문항 테스트",
      "테스트 결과에 맞는 초콜릿 4종으로 간식컵 완성",
      "간식컵 바닥의 랜덤 MBTI 스티커와 테스트 결과의 일치 알파벳 수에 따른 선착순 경품 지급",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418103530" },
  },

  {
    id: "json-40-day1-e15",
    locationId: "e15",
    date: "day1",
    name: "이과대학 학생회 SEQUENCE",
    category: "음식, 체험, 굿즈",
    description:
      "<행운 연구소>에서 축제 상황에 맞춘 행운 실험과 충전 음료, 굿즈를 즐길 수 있는 부스",
    menu: [
      "행운 실험실 3,000원",
      "레몬 에이드 2,500원",
      "자몽 에이드 2,500원",
      "청포도 에이드 2,500원",
      "행운 기록실 1,000원",
    ],
    events: [
      "인간챗팟 게임을 통한 오늘의 행운 수치 확인 및 행운 실험",
      "실험 참가자 중 3명을 랜덤 추첨해 과일 일치 개수에 따른 상품 증정",
      "행운 기록실에서 네 컷 프레임으로 행운의 순간 기록",
      "럭키드로우 3,000원",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/501300/v/418122091" },
  },
  {
    id: "json-40-day1-e16",
    locationId: "e16",
    date: "day1",
    name: "이과대학 학생회 SEQUENCE",
    category: "음식, 체험, 굿즈",
    description:
      "<행운 연구소>에서 축제 상황에 맞춘 행운 실험과 충전 음료, 굿즈를 즐길 수 있는 부스",
    menu: [
      "행운 실험실 3,000원",
      "레몬 에이드 2,500원",
      "자몽 에이드 2,500원",
      "청포도 에이드 2,500원",
      "행운 기록실 1,000원",
    ],
    events: [
      "인간챗팟 게임을 통한 오늘의 행운 수치 확인 및 행운 실험",
      "실험 참가자 중 3명을 랜덤 추첨해 과일 일치 개수에 따른 상품 증정",
      "행운 기록실에서 네 컷 프레임으로 행운의 순간 기록",
      "럭키드로우 3,000원",
    ],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/501300/v/418122091" },
  },

  {
    id: "json-45-day1-e19",
    source: "official",
    locationId: "e19",
    date: "day1",
    name: "묵아랑",
    category: "체험",
    description: "DIY 실링왁스, 비즈팔찌, 키링 만들기 체험",
    menu: ["실링왁스 2,000원", "비즈팔찌 3,000원", "키링 3,000원"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
  },
  {
    id: "json-45-day1-e20",
    source: "official",
    locationId: "e20",
    date: "day1",
    name: "묵아랑",
    category: "체험",
    description: "DIY 실링왁스, 비즈팔찌, 키링 만들기 체험",
    menu: ["실링왁스 2,000원", "비즈팔찌 3,000원", "키링 3,000원"],
    operatingHours: "9월 16일(수) 10:00 ~ 16:00",
  },

  // 제2캠퍼스 E구역 전체 배치도 기준: 상세 데이터가 없어도 이름/위치가 표시되도록 등록한다.
  { id: "layout-day1-e05", locationId: "e05", date: "day1", name: "숙명 CCC" },
  { id: "layout-day1-e06", locationId: "e06", date: "day1", name: "숙명 CCC" },
  {
    id: "layout-day1-e13",
    locationId: "e13",
    date: "day1",
    name: "자유전공학부 비상대책위원회",
  },
  {
    id: "layout-day1-e15",
    locationId: "e15",
    date: "day1",
    name: "이과대학 학생회 SEQUENCE",
  },
  {
    id: "layout-day1-e16",
    locationId: "e16",
    date: "day1",
    name: "이과대학 학생회 SEQUENCE",
  },

  { id: "layout-day2-e05", locationId: "e05", date: "day2", name: "숙명 CCC" },
  { id: "layout-day2-e06", locationId: "e06", date: "day2", name: "숙명 CCC" },
  {
    id: "layout-day2-e13",
    locationId: "e13",
    date: "day2",
    name: "자유전공학부 비상대책위원회",
  },
  {
    id: "json-45-day2-e15",
    source: "official",
    locationId: "e15",
    date: "day2",
    name: "역사문화학과 학생회 사랑",
    category: "음식, 굿즈",
    description:
      "음료는 역사적 사건, 국가 또는 인물을 모티브로 기획되며, 메뉴별 역사적 의미를 함께 소개할 예정",
    menu: [
      "슬러시",
      "에이드",
      "커피",
      "만점 부적(한능검, 장원급제, 면접, 지혜, 용기, 불로초)",
    ],
    events: ["역사적 의미를 담은 음료 및 굿즈 판매"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
  },
  {
    id: "json-45-day2-e16",
    source: "official",
    locationId: "e16",
    date: "day2",
    name: "역사문화학과 학생회 사랑",
    category: "음식, 굿즈",
    description:
      "음료는 역사적 사건, 국가 또는 인물을 모티브로 기획되며, 메뉴별 역사적 의미를 함께 소개할 예정",
    menu: [
      "슬러시",
      "에이드",
      "커피",
      "만점 부적(한능검, 장원급제, 면접, 지혜, 용기, 불로초)",
    ],
    events: ["역사적 의미를 담은 음료 및 굿즈 판매"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
  },

  // 상세 데이터 추가 — 직접 조사 기준 (직접 조사 데이터 우선)
  {
    id: "json-41-day2-a10",
    source: "official",
    locationId: "a10",
    date: "day2",
    name: "반극회",
    category: "체험",
    description:
      "선택형 질문에 답하면 나와 어울리는 연극 작품 또는 연극 속 캐릭터를 추천하는 프로그램",
    events: ["SNS 눈송이 액백 증정"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
  },
  {
    id: "json-42-day2-b04",
    source: "official",
    locationId: "b04",
    date: "day2",
    name: "so9chi2",
    category: "굿즈",
    description: "핸드메이드 어패럴 판매",
    menu: ["멀티밴드", "초커", "브로치"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
  },
  {
    id: "json-43-day2-b05",
    source: "direct",
    locationId: "b05",
    date: "day2",
    name: "URINK",
    category: "체험",
    description:
      "외국어·문화 관련 게임과 U&I 링링부스를 통해 새로운 친구를 만나는 글로벌 버디 리더십그룹 부스",
    events: [
      "틱톡 외국어 챌린지 게임 — 외국어로 인사말 따라하기",
      "랜드마크/음식 사진 보고 나라 맞히기",
      "U&I 링링부스 — 자신의 소개 포스터를 작성하고 나와 잘 맞는 재학생 또는 교환학생 친구 만나기",
    ],
    menu: ["이벤트 상품 — 스티커, 키링, 간식(기념품)"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/129540/v/418098110" },
  },
  {
    id: "json-43-day2-b06",
    source: "direct",
    locationId: "b06",
    date: "day2",
    name: "URINK",
    category: "체험",
    description:
      "외국어·문화 관련 게임과 U&I 링링부스를 통해 새로운 친구를 만나는 글로벌 버디 리더십그룹 부스",
    events: [
      "틱톡 외국어 챌린지 게임 — 외국어로 인사말 따라하기",
      "랜드마크/음식 사진 보고 나라 맞히기",
      "U&I 링링부스 — 자신의 소개 포스터를 작성하고 나와 잘 맞는 재학생 또는 교환학생 친구 만나기",
    ],
    menu: ["이벤트 상품 — 스티커, 키링, 간식(기념품)"],
    operatingHours: "9월 17일(목) 10:00 ~ 16:00",
    promoLinks: { everytime: "https://everytime.kr/129540/v/418098110" },
  },

  {
    id: "json-44-day1-e01",
    source: "direct",
    locationId: "e01",
    date: "day1",
    name: "공군학군단",
    category: "홍보",
    description:
      "공군 ROTC 정보를 알아보고 러닝양말·지비츠 등 기념품과 하늘이 마스코트 폴라로이드 촬영을 즐길 수 있는 홍보 부스",
    events: [
      "러닝양말 증정",
      "공군에서만 받을 수 있는 지비츠 제공",
      "하늘이 마스코트와 함께하는 폴라로이드 촬영",
      "숙명여대 공군 학군단 입단 상담 신청",
      "공군 학군단에 대한 정보 및 궁금한 점 상담",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {
      everytime: "https://everytime.kr/258594/v/418217950",
    },
  },
  {
    id: "json-44-day2-e01",
    source: "direct",
    locationId: "e01",
    date: "day2",
    name: "공군학군단",
    category: "홍보",
    description:
      "공군 ROTC 정보를 알아보고 러닝양말·지비츠 등 기념품과 하늘이 마스코트 폴라로이드 촬영을 즐길 수 있는 홍보 부스",
    events: [
      "러닝양말 증정",
      "공군에서만 받을 수 있는 지비츠 제공",
      "하늘이 마스코트와 함께하는 폴라로이드 촬영",
      "숙명여대 공군 학군단 입단 상담 신청",
      "공군 학군단에 대한 정보 및 궁금한 점 상담",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {
      everytime: "https://everytime.kr/258594/v/418217950",
    },
  },
  {
    id: "json-44-day1-e02",
    source: "direct",
    locationId: "e02",
    date: "day1",
    name: "공군학군단",
    category: "홍보",
    description:
      "공군 ROTC 정보를 알아보고 러닝양말·지비츠 등 기념품과 하늘이 마스코트 폴라로이드 촬영을 즐길 수 있는 홍보 부스",
    events: [
      "러닝양말 증정",
      "공군에서만 받을 수 있는 지비츠 제공",
      "하늘이 마스코트와 함께하는 폴라로이드 촬영",
      "숙명여대 공군 학군단 입단 상담 신청",
      "공군 학군단에 대한 정보 및 궁금한 점 상담",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {
      everytime: "https://everytime.kr/258594/v/418217950",
    },
  },
  {
    id: "json-44-day2-e02",
    source: "direct",
    locationId: "e02",
    date: "day2",
    name: "공군학군단",
    category: "홍보",
    description:
      "공군 ROTC 정보를 알아보고 러닝양말·지비츠 등 기념품과 하늘이 마스코트 폴라로이드 촬영을 즐길 수 있는 홍보 부스",
    events: [
      "러닝양말 증정",
      "공군에서만 받을 수 있는 지비츠 제공",
      "하늘이 마스코트와 함께하는 폴라로이드 촬영",
      "숙명여대 공군 학군단 입단 상담 신청",
      "공군 학군단에 대한 정보 및 궁금한 점 상담",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 10:00 ~ 16:00",
    promoLinks: {
      everytime: "https://everytime.kr/258594/v/418217950",
    },
  },

  // 전체 배치도에 이름과 위치가 공개된 부스 중 상세 데이터가 아직 없는 슬롯도
  // 지도에서 선택할 수 있도록 이름/위치만 등록한다.
  { id: "layout-day1-a06", locationId: "a06", date: "day1", name: "FD’link" },
  { id: "layout-day1-a11", locationId: "a11", date: "day1", name: "ESCA" },
  { id: "layout-day1-a12", locationId: "a12", date: "day1", name: "ESCA" },

  // 9월 16일 밤 부스 — 16:30~20:00 운영 정보
  {
    id: "json-night-day1-c01",
    locationId: "c01",
    date: "day1",
    session: "night",
    name: "엉뚱한사람들",
    category: "체험, 게임·이벤트",
    description:
      "말로 하는 인형뽑기와 DIY 커스텀 키캡 키링 만들기를 즐기는 부스",
    events: [
      "말로 하는 인형뽑기",
      "DIY 커스텀 키캡 키링 (눈송이, LED 액세서리 파츠, 3D 프린팅 키캡)",
    ],
    operatingHours: "9월 16일(수) 16:30 ~ 20:00",
  },
  {
    id: "json-night-day1-c02",
    locationId: "c02",
    date: "day1",
    session: "night",
    name: "엉뚱한사람들",
    category: "체험, 게임·이벤트",
    description:
      "말로 하는 인형뽑기와 DIY 커스텀 키캡 키링 만들기를 즐기는 부스",
    events: [
      "말로 하는 인형뽑기",
      "DIY 커스텀 키캡 키링 (눈송이, LED 액세서리 파츠, 3D 프린팅 키캡)",
    ],
    operatingHours: "9월 16일(수) 16:30 ~ 20:00",
  },
  {
    id: "json-night-day1-c03",
    locationId: "c03",
    date: "day1",
    session: "night",
    name: "설미",
    category: "굿즈",
    description:
      "유화/아크릴 물감으로 그린 엽서와 직접 제작한 캐리커쳐, 페이스페인팅을 운영하는 중앙동아리 부스",
    menu: [
      "엽서 1장 1,000원",
      "엽서 6장 세트 5,000원",
      "캐리커쳐 2컷 1,500원",
      "페이스페인팅 1,000원",
    ],
    operatingHours: "9월 16일(수) 16:30 ~ 20:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418173848" },
  },
  {
    id: "json-night-day1-c04",
    locationId: "c04",
    date: "day1",
    session: "night",
    name: "설미",
    category: "굿즈",
    description:
      "유화/아크릴 물감으로 그린 엽서와 직접 제작한 캐리커쳐, 페이스페인팅을 운영하는 중앙동아리 부스",
    menu: [
      "엽서 1장 1,000원",
      "엽서 6장 세트 5,000원",
      "캐리커쳐 2컷 1,500원",
      "페이스페인팅 1,000원",
    ],
    operatingHours: "9월 16일(수) 16:30 ~ 20:00",
    promoLinks: { everytime: "https://everytime.kr/255673/v/418173848" },
  },
  {
    id: "json-night-day1-c05",
    locationId: "c05",
    date: "day1",
    session: "night",
    name: "SCSM",
    category: "굿즈",
    description: "다양한 굿즈를 판매하는 중앙동아리 부스",
    menu: [
      "스티커",
      "북마크",
      "비즈자수 팔찌",
      "키링",
      "부적",
      "미니 메시지 병",
    ],
    operatingHours: "9월 16일(수) 16:30 ~ 20:00",
  },
  {
    id: "json-night-day1-c06",
    locationId: "c06",
    date: "day1",
    session: "night",
    name: "SCSM",
    category: "굿즈",
    description: "다양한 굿즈를 판매하는 중앙동아리 부스",
    menu: [
      "스티커",
      "북마크",
      "비즈자수 팔찌",
      "키링",
      "부적",
      "미니 메시지 병",
    ],
    operatingHours: "9월 16일(수) 16:30 ~ 20:00",
  },
  // 9월 16일 밤 부스 — 최신 전체 배치도 기준. 상세 정보는 아직 공개되지 않아 이름/위치만 반영.
  {
    id: "layout-night-day1-c01",
    locationId: "c01",
    date: "day1",
    session: "night",
    name: "엉뚱한 사람들",
  },
  {
    id: "layout-night-day1-c02",
    locationId: "c02",
    date: "day1",
    session: "night",
    name: "엉뚱한 사람들",
  },
  {
    id: "layout-night-day1-c03",
    locationId: "c03",
    date: "day1",
    session: "night",
    name: "설미",
  },
  {
    id: "layout-night-day1-c04",
    locationId: "c04",
    date: "day1",
    session: "night",
    name: "설미",
  },
  {
    id: "layout-night-day1-c05",
    locationId: "c05",
    date: "day1",
    session: "night",
    name: "SCSM",
  },
  {
    id: "layout-night-day1-c06",
    locationId: "c06",
    date: "day1",
    session: "night",
    name: "SCSM",
  },
  {
    id: "layout-night-day1-c07",
    locationId: "c07",
    date: "day1",
    session: "night",
    name: "UNSA",
  },
  {
    id: "layout-night-day1-c08",
    locationId: "c08",
    date: "day1",
    session: "night",
    name: "UNSA",
  },
  {
    id: "layout-night-day1-c09",
    locationId: "c09",
    date: "day1",
    session: "night",
    name: "경영연구학회 청명",
  },
  {
    id: "layout-night-day1-c10",
    locationId: "c10",
    date: "day1",
    session: "night",
    name: "경영연구학회 청명",
  },
  {
    id: "layout-night-day1-c11",
    locationId: "c11",
    date: "day1",
    session: "night",
    name: "경영학부 학회 향영",
  },
  {
    id: "layout-night-day1-c12",
    locationId: "c12",
    date: "day1",
    session: "night",
    name: "경영학부 학회 향영",
  },
];

export const schedules: ScheduleItem[] = [
  {
    date: "day1",
    time: "16:00~21:00",
    title: "무대 공연",
    place: "제1캠퍼스 야외주차장 본무대",
    description: "AXIOM · 이카루스 · 코드BLUE · 청월대전 · 설렘 · NIVIS · 초청 아티스트",
    programs: [
      { time: "16:13~16:31", performer: "AXIOM (밴드)", content: "Square(2017)-백예린 / 사랑을 전하고 싶다던가-아이묭 / 비틀비틀 짜증-한로로 / HAPPY-DAY6" },
      { time: "16:34~16:55", performer: "이카루스 (밴드)", content: "Let's Get The Party Started-Tom Morello / Ohio-King Princess / Psycho-Muse / Rock You Like a Hurricane-Scorpions" },
      { time: "17:02~17:27", performer: "코드BLUE (어쿠스틱밴드)", content: "누구없소-이무진 / LOVE ME RIGHT-EXO / Pain-하현상 / Speechless-Naomi Scott / 바람-유다빈밴드" },
      { time: "17:40~18:25", performer: "청월대전 (프로그램)", content: "가면으로 정체를 숨긴 참가자들의 노래 무대 · 관객 실시간 온라인 투표로 순위 결정" },
      { time: "18:27~18:47", performer: "설렘 (중앙뮤지컬동아리)", content: "Defying Gravity / A Million Dreams / Sweet Little Sister / Seasons of Love" },
      { time: "18:50~19:17", performer: "니비스응원단 (댄스)", content: "It's My Life / 질풍가도 / 예술이야 / 시간을 달려서 / Force Unite / 날개 / 그대에게" },
      { time: "19:30~21:00", performer: "초청 아티스트", content: "WOOAH / STAYC / YENA" },
    ],
  },
  {
    date: "day2",
    time: "16:20~21:00",
    title: "무대 공연",
    place: "제1캠퍼스 야외주차장 본무대",
    description: "DESTINY · 송이무사 · HADA · MAX · 궁중택일 · 초청 아티스트",
    programs: [
      { time: "16:25~16:53", performer: "DESTINY (밴드)", content: "주제는 사랑-까치산 / 청룡-이츠 / Stay with Me-Miki Matsubara / 친애하는 소년이여-Hump Back / POP UP-Dragon Pony / 돌려주고 싶었던-이승윤" },
      { time: "16:57~17:14", performer: "송이무사 (밴드)", content: "Hi Bully-터치드 / Bang Bang-Green Day / Happy Day-레퍼터리" },
      { time: "17:26~17:42", performer: "HADA (댄스)", content: "CORTIS-REDRED / Cockiness-Extra L / AESPA-WDA / EXO-Love Me Right" },
      { time: "17:46~18:15", performer: "MAX (댄스)", content: "① 팝핑: Happy Face-Cirque-Good Time / ② 왁킹: A Pale-Salvaje / ③ 코레오C: Hip Hop Hooray-Time 4 Sum Aksion-HOOLIGAN G4 (Swiim Remix)-Talk Talk-Baby / ⑤ 코레오B: Golden Hour-Love Wins All / ⑥ 락킹: Phenomenal-Labour of Love / ⑦ 크럼프: KinjaBang-Purple Lamborghini / ⑧ 코레오A: Gimme More-Toxic / ⑨ 25기 기수곡: Blade-Zen(MMA2025 Remix)" },
      { time: "18:20~19:25", performer: "궁중택일 (프로그램)", content: "동문 선배님과 함께하는 밸런스 게임 토크 · 사전 접수 사연 소개" },
      { time: "19:30~21:00", performer: "초청 아티스트", content: "H1GHTS / FIFTYFIFTY / 프로미스나인 (FROMIS_9)" },
    ],
  },
  {
    date: "day1",
    time: "13:00~15:25",
    title: "버스킹 공연 · 1부",
    place: "제1캠퍼스 원형극장",
    description: "초록공룡 · 체리송이 · 미정 · 박치더락",
    programs: [
      { time: "13:01~13:16", performer: "초록공룡 (보컬)", content: "Square(2017)-백예린 / 2002-Anne-Marie / Cruel Summer-Taylor Swift / 한 페이지가 될 수 있게-DAY6" },
      { time: "13:18~13:38", performer: "체리송이 (보컬)", content: "〈브론테〉 우리만의 놀이 / 〈수레바퀴 아래서〉 구름 / 〈원스 온 디스 아일랜드〉 Waiting For Life / 〈비틀즈〉 Dead Mom / 〈도리안 그레이〉 돌아올 그날까지" },
      { time: "14:44~15:01", performer: "미정 (밴드)", content: "Happy Day-레퍼트리 / Can't Stop-Red Hot Chili Peppers / LETTER-유다빈밴드 / Sk8er Boi-Avril Lavigne / The Great Escape-Boys Like Girls" },
      { time: "15:03~15:25", performer: "박치더락 (밴드)", content: "Butter-Fly-선영호 / Don't Say \"Lazy\"-桜高軽音部 / 달춤-터치드 / Flashback-엔플라잉" },
    ],
  },
  {
    date: "day2",
    time: "14:30~15:14",
    title: "버스킹 공연",
    place: "제1캠퍼스 새힘관 잔디밭",
    description: "설화연 · 숙풍",
    programs: [
      { time: "14:30~14:47", performer: "설화연 (태권도)", content: "Uptown Funk / HOT / Tempo / 태극 6장 / 태극 8장 / 단체 격파" },
      { time: "14:52~15:14", performer: "숙풍 (사물놀이)", content: "굿내는가락 / 반풍류 / 칠채 / 호허 / 미지기 / 재상놀이 / 미지기 연산 / 방울진" },
    ],
  },
];
