import type { Booth, BoothLocation, ScheduleItem } from "./types";

export const locations: BoothLocation[] = [
  {
    id: "a01",
    campus: "campus1",
    code: "A01",
    latitude: 37.546426,
    longitude: 126.964381,
    mapPosition: { x: 50.3157, y: 36.7139},
    mapSize: { width: 44, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a02",
    campus: "campus1",
    code: "A02",
    latitude: 37.546426,
    longitude: 126.964434,
    mapPosition: { x: 53.1901, y: 36.7139},
    mapSize: { width: 43, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a03",
    campus: "campus1",
    code: "A03",
    latitude: 37.546426,
    longitude: 126.964486,
    mapPosition: { x: 56.1043, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a04",
    campus: "campus1",
    code: "A04",
    latitude: 37.546426,
    longitude: 126.964538,
    mapPosition: { x: 58.9754, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a05",
    campus: "campus1",
    code: "A05",
    latitude: 37.546426,
    longitude: 126.964591,
    mapPosition: { x: 61.8718, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a06",
    campus: "campus1",
    code: "A06",
    latitude: 37.546426,
    longitude: 126.964643,
    mapPosition: { x: 64.7237, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a07",
    campus: "campus1",
    code: "A07",
    latitude: 37.546426,
    longitude: 126.964695,
    mapPosition: { x: 67.6160, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a08",
    campus: "campus1",
    code: "A08",
    latitude: 37.546426,
    longitude: 126.964748,
    mapPosition: { x: 70.4741, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a09",
    campus: "campus1",
    code: "A09",
    latitude: 37.546426,
    longitude: 126.9648,
    mapPosition: { x: 73.3260, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a10",
    campus: "campus1",
    code: "A10",
    latitude: 37.546426,
    longitude: 126.964852,
    mapPosition: { x: 76.0673, y: 36.7139},
    mapSize: { width: 42, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a11",
    campus: "campus1",
    code: "A11",
    latitude: 37.546426,
    longitude: 126.964904,
    mapPosition: { x: 78.8076, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a12",
    campus: "campus1",
    code: "A12",
    latitude: 37.546426,
    longitude: 126.964957,
    mapPosition: { x: 81.6683, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a13",
    campus: "campus1",
    code: "A13",
    latitude: 37.546426,
    longitude: 126.965009,
    mapPosition: { x: 84.5383, y: 36.7139},
    mapSize: { width: 40, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "a14",
    campus: "campus1",
    code: "A14",
    latitude: 37.546426,
    longitude: 126.965061,
    mapPosition: { x: 87.4142, y: 36.7139},
    mapSize: { width: 41, height: 33 },
    location: "순헌관 앞",
  },
  {
    id: "b01",
    campus: "campus1",
    code: "B01",
    latitude: 37.546426,
    longitude: 126.963746,
    mapPosition: { x: 23.5817, y: 36.7139},
    mapSize: { width: 51, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b02",
    campus: "campus1",
    code: "B02",
    latitude: 37.546426,
    longitude: 126.963814,
    mapPosition: { x: 27.2226, y: 36.7139},
    mapSize: { width: 51, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b03",
    campus: "campus1",
    code: "B03",
    latitude: 37.546426,
    longitude: 126.963882,
    mapPosition: { x: 30.8021, y: 36.7139},
    mapSize: { width: 49, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b04",
    campus: "campus1",
    code: "B04",
    latitude: 37.546426,
    longitude: 126.96395,
    mapPosition: { x: 34.2495, y: 36.7139},
    mapSize: { width: 49, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b05",
    campus: "campus1",
    code: "B05",
    latitude: 37.546426,
    longitude: 126.964018,
    mapPosition: { x: 37.6408, y: 36.7139},
    mapSize: { width: 49, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "b06",
    campus: "campus1",
    code: "B06",
    latitude: 37.546426,
    longitude: 126.964086,
    mapPosition: { x: 40.9615, y: 36.7139},
    mapSize: { width: 48, height: 33 },
    location: "진리관 앞",
  },
  {
    id: "c01",
    campus: "campus1",
    code: "C01",
    latitude: 37.545951,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 44.3192},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c02",
    campus: "campus1",
    code: "C02",
    latitude: 37.545906,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 47.5207},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c03",
    campus: "campus1",
    code: "C03",
    latitude: 37.545861,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 50.7152},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c04",
    campus: "campus1",
    code: "C04",
    latitude: 37.545816,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 53.8589},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c05",
    campus: "campus1",
    code: "C05",
    latitude: 37.545771,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 56.9810},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c06",
    campus: "campus1",
    code: "C06",
    latitude: 37.545726,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 60.1198},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c07",
    campus: "campus1",
    code: "C07",
    latitude: 37.545681,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 63.2759},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c08",
    campus: "campus1",
    code: "C08",
    latitude: 37.545636,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 66.3672},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c09",
    campus: "campus1",
    code: "C09",
    latitude: 37.545592,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 69.4824},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c10",
    campus: "campus1",
    code: "C10",
    latitude: 37.545547,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 72.6074},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c11",
    campus: "campus1",
    code: "C11",
    latitude: 37.545502,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 75.7324},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "c12",
    campus: "campus1",
    code: "C12",
    latitude: 37.545457,
    longitude: 126.963638,
    mapPosition: { x: 27.3047, y: 78.8574},
    mapSize: { width: 54, height: 30 },
    location: "명신관 앞",
  },
  {
    id: "d01",
    campus: "campus1",
    code: "D01",
    latitude: 37.545412,
    longitude: 126.964522,
    mapPosition: { x: 32.8255, y: 79.3408},
    mapSize: { width: 51, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d02",
    campus: "campus1",
    code: "D02",
    latitude: 37.545412,
    longitude: 126.964595,
    mapPosition: { x: 36.3021, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d03",
    campus: "campus1",
    code: "D03",
    latitude: 37.545412,
    longitude: 126.964668,
    mapPosition: { x: 39.7917, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d04",
    campus: "campus1",
    code: "D04",
    latitude: 37.545412,
    longitude: 126.964741,
    mapPosition: { x: 43.2617, y: 79.3408},
    mapSize: { width: 49, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d05",
    campus: "campus1",
    code: "D05",
    latitude: 37.545412,
    longitude: 126.964813,
    mapPosition: { x: 46.7122, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d06",
    campus: "campus1",
    code: "D06",
    latitude: 37.545412,
    longitude: 126.964886,
    mapPosition: { x: 50.1432, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d07",
    campus: "campus1",
    code: "D07",
    latitude: 37.545412,
    longitude: 126.964959,
    mapPosition: { x: 53.6068, y: 79.3408},
    mapSize: { width: 49, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "d08",
    campus: "campus1",
    code: "D08",
    latitude: 37.545412,
    longitude: 126.965032,
    mapPosition: { x: 57.0638, y: 79.3408},
    mapSize: { width: 50, height: 33 },
    location: "명신 언덕",
  },
  {
    id: "e01",
    campus: "campus2",
    code: "E01",
    latitude: 37.544311,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 44.9121},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e02",
    campus: "campus2",
    code: "E02",
    latitude: 37.544346,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 48.4863},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e03",
    campus: "campus2",
    code: "E03",
    latitude: 37.54438,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 52.0508},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e04",
    campus: "campus2",
    code: "E04",
    latitude: 37.544415,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 55.7129},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e05",
    campus: "campus2",
    code: "E05",
    latitude: 37.54445,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 59.2969},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e06",
    campus: "campus2",
    code: "E06",
    latitude: 37.544485,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 62.8906},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e07",
    campus: "campus2",
    code: "E07",
    latitude: 37.54452,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 66.6016},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e08",
    campus: "campus2",
    code: "E08",
    latitude: 37.544555,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 70.3027},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e09",
    campus: "campus2",
    code: "E09",
    latitude: 37.54459,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 74.0332},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e10",
    campus: "campus2",
    code: "E10",
    latitude: 37.544625,
    longitude: 126.963967,
    mapPosition: { x: 54.1374, y: 77.7734},
    mapSize: { width: 58, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e11",
    campus: "campus2",
    code: "E11",
    latitude: 37.544311,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 44.9121},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e12",
    campus: "campus2",
    code: "E12",
    latitude: 37.544346,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 48.4863},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e13",
    campus: "campus2",
    code: "E13",
    latitude: 37.54438,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 52.0508},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e14",
    campus: "campus2",
    code: "E14",
    latitude: 37.544415,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 55.7129},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e15",
    campus: "campus2",
    code: "E15",
    latitude: 37.54445,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 59.2969},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e16",
    campus: "campus2",
    code: "E16",
    latitude: 37.544485,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 62.8906},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e17",
    campus: "campus2",
    code: "E17",
    latitude: 37.54452,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 66.6016},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e18",
    campus: "campus2",
    code: "E18",
    latitude: 37.544555,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 70.3027},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e19",
    campus: "campus2",
    code: "E19",
    latitude: 37.54459,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 74.0332},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
  {
    id: "e20",
    campus: "campus2",
    code: "E20",
    latitude: 37.544625,
    longitude: 126.964171,
    mapPosition: { x: 59.2969, y: 77.7734},
    mapSize: { width: 57, height: 33 },
    location: "눈꽃광장 실내",
  },
];

export const booths: Booth[] = [
  {
    id: "a01-day1",
    locationId: "a01",
    date: "day1",
    name: "SID",
    category: "굿즈 판매",
    description:
      "산업디자인과 학회 SID — 120주년 기념 키링 (블루, 그레이, 블랙 3가지 컬러)",
    events: [
      "인스타그램 스토리에 @sid_smid 태그 및 게시물 업로드 시 SID만의 눈송이 스티커 증정",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 양일",
  },
  {
    id: "a02-day1",
    locationId: "a02",
    date: "day1",
    name: "설화연",
    category: "굿즈 판매 · 이벤트",
    description:
      "중앙태권도동아리 설화연 — 태권도 눈송이부터 기본 눈송이, 시험 과제까지 총 5가지 픽셀 키캡 중 원하는 2가지를 골라 만드는 키캡 키링",
    menu: ["2구 키캡 키링 3,500원 (2개 구매 시 6,500원)"],
    events: [
      "키캡 구매 인증샷을 설화연 공식 계정 태그 후 스토리 업로드 시 추첨을 통해 올리브영 5,000원 기프티콘 증정 (3명)",
    ],
    operatingHours: "9/16(수) 10:00~16:00, 9/17(목) 10:00~13:00",
  },
  {
    id: "a03-day1",
    locationId: "a03",
    date: "day1",
    name: "AIESEC",
    category: "먹거리 · 체험/이벤트",
    description:
      "중앙동아리 AIESEC — 시원달달한 과일 화채 판매 및 보드게임, 해외교류 프로그램 상담 부스",
    menu: ["시원달달한 과일 화채"],
    events: [
      "게임 부스 아이섹마블 — 주사위를 굴리며 AIESEC과 SDGs를 알아보는 보드게임 (참여 시 간식 꾸러미 증정)",
      "해외 봉사 및 해외 인턴십 상담 진행",
    ],
    operatingHours: "9/16(수)~9/17(목) 10:00~16:00",
  },
  {
    id: "a04-day1",
    locationId: "a04",
    date: "day1",
    name: "AIESEC",
    category: "먹거리 · 체험/이벤트",
    description:
      "중앙동아리 AIESEC — 시원달달한 과일 화채 판매 및 보드게임, 해외교류 프로그램 상담 부스",
    menu: ["시원달달한 과일 화채"],
    events: [
      "게임 부스 아이섹마블 — 주사위를 굴리며 AIESEC과 SDGs를 알아보는 보드게임 (참여 시 간식 꾸러미 증정)",
      "해외 봉사 및 해외 인턴십 상담 진행",
    ],
    operatingHours: "9/16(수)~9/17(목) 10:00~16:00",
  },
  {
    id: "a05-day1",
    locationId: "a05",
    date: "day1",
    name: "중앙뮤지컬동아리 설렘",
  },
  {
    id: "a06-day1",
    locationId: "a06",
    date: "day1",
    name: "FD'link",
  },
  {
    id: "a07-day1",
    locationId: "a07",
    date: "day1",
    name: "아동복지학부 학회 숙나래",
    category: "먹거리 · 굿즈 판매",
    description:
      "아동복지학부 아동문학학회 숙나래 — 수제 레몬에이드와 동화 속 캐릭터 굿즈, 동화책 판매 및 럭키드로우 이벤트",
    menu: [
      "수기 레몬에이드 2,000원",
      "나래 블루레몬에이드 2,000원 (개인 텀블러 지참 시 200원 할인)",
    ],
    events: [
      "굿즈 6,000원 이상 구매 시 100% 당첨 럭키드로우 참여",
      "아복 학생들이 직접 만든 동화책 판매",
    ],
    operatingHours: "9월 16일(수) 10:00~16:00",
  },
  {
    id: "a08-day1",
    locationId: "a08",
    date: "day1",
    name: "아동복지학부 학회 숙나래",
    category: "먹거리 · 굿즈 판매",
    description:
      "아동복지학부 아동문학학회 숙나래 — 수제 레몬에이드와 동화 속 캐릭터 굿즈, 동화책 판매 및 럭키드로우 이벤트",
    menu: [
      "수기 레몬에이드 2,000원",
      "나래 블루레몬에이드 2,000원 (개인 텀블러 지참 시 200원 할인)",
    ],
    events: [
      "굿즈 6,000원 이상 구매 시 100% 당첨 럭키드로우 참여",
      "아복 학생들이 직접 만든 동화책 판매",
    ],
    operatingHours: "9월 16일(수) 10:00~16:00",
  },
  {
    id: "a09-day1",
    locationId: "a09",
    date: "day1",
    name: "가족자원경영학과 학회 S.O.F",
    category: "체험/이벤트",
    description:
      "가족자원경영학과 학회 S.O.F — S.O.F 마음우체국, 나만의 볼펜 만들기 및 가족 문자 이벤트",
    events: ["볼펜 만들기 및 가족 문자 인증 시 달콤한 간식 증정"],
    operatingHours: "9/16(수) 10:00~16:00",
  },
  {
    id: "a10-day1",
    locationId: "a10",
    date: "day1",
    name: "가족자원경영학과 학회 S.O.F",
    category: "체험/이벤트",
    description:
      "가족자원경영학과 학회 S.O.F — S.O.F 마음우체국, 나만의 볼펜 만들기 및 가족 문자 이벤트",
    events: ["볼펜 만들기 및 가족 문자 인증 시 달콤한 간식 증정"],
    operatingHours: "9/16(수) 10:00~16:00",
  },
  {
    id: "a11-day1",
    locationId: "a11",
    date: "day1",
    name: "ESCA",
  },
  {
    id: "a12-day1",
    locationId: "a12",
    date: "day1",
    name: "ESCA",
  },
  {
    id: "a13-day1",
    locationId: "a13",
    date: "day1",
    name: "데스티니",
    category: "공연/이벤트",
    description:
      "DESTINY SUMMER FESTIVAL — 밴드 데스티니 부스 운영 및 특별 무대 안내",
    operatingHours: "9월 16일(수) 10:00~16:00",
  },
  {
    id: "a14-day1",
    locationId: "a14",
    date: "day1",
    name: "데스티니",
    category: "공연/이벤트",
    description:
      "DESTINY SUMMER FESTIVAL — 밴드 데스티니 부스 운영 및 특별 무대 안내",
    operatingHours: "9월 16일(수) 10:00~16:00",
  },
  {
    id: "a01-day2",
    locationId: "a01",
    date: "day2",
    name: "SID",
    category: "굿즈 판매",
    description:
      "산업디자인과 학회 SID — 120주년 기념 키링 (블루, 그레이, 블랙 3가지 컬러)",
    events: [
      "인스타그램 스토리에 @sid_smid 태그 및 게시물 업로드 시 SID만의 눈송이 스티커 증정",
    ],
    operatingHours: "9월 16일(수) ~ 9월 17일(목) 양일",
  },
  {
    id: "a02-day2",
    locationId: "a02",
    date: "day2",
    name: "설화연",
    category: "굿즈 판매 · 이벤트",
    description:
      "중앙태권도동아리 설화연 — 태권도 눈송이부터 기본 눈송이, 시험 과제까지 총 5가지 픽셀 키캡 중 원하는 2가지를 골라 만드는 키캡 키링",
    menu: ["2구 키캡 키링 3,500원 (2개 구매 시 6,500원)"],
    events: [
      "키캡 구매 인증샷을 설화연 공식 계정 태그 후 스토리 업로드 시 추첨을 통해 올리브영 5,000원 기프티콘 증정 (3명)",
    ],
    operatingHours: "9/16(수) 10:00~16:00, 9/17(목) 10:00~13:00",
  },
  {
    id: "a03-day2",
    locationId: "a03",
    date: "day2",
    name: "AIESEC",
    category: "먹거리 · 체험/이벤트",
    description:
      "중앙동아리 AIESEC — 시원달달한 과일 화채 판매 및 보드게임, 해외교류 프로그램 상담 부스",
    menu: ["시원달달한 과일 화채"],
    events: [
      "게임 부스 아이섹마블 — 주사위를 굴리며 AIESEC과 SDGs를 알아보는 보드게임 (참여 시 간식 꾸러미 증정)",
      "해외 봉사 및 해외 인턴십 상담 진행",
    ],
    operatingHours: "9/16(수)~9/17(목) 10:00~16:00",
  },
  {
    id: "a04-day2",
    locationId: "a04",
    date: "day2",
    name: "AIESEC",
    category: "먹거리 · 체험/이벤트",
    description:
      "중앙동아리 AIESEC — 시원달달한 과일 화채 판매 및 보드게임, 해외교류 프로그램 상담 부스",
    menu: ["시원달달한 과일 화채"],
    events: [
      "게임 부스 아이섹마블 — 주사위를 굴리며 AIESEC과 SDGs를 알아보는 보드게임 (참여 시 간식 꾸러미 증정)",
      "해외 봉사 및 해외 인턴십 상담 진행",
    ],
    operatingHours: "9/16(수)~9/17(목) 10:00~16:00",
  },
  {
    id: "a05-day2",
    locationId: "a05",
    date: "day2",
    name: "중앙뮤지컬동아리 설렘",
  },
  {
    id: "a06-day2",
    locationId: "a06",
    date: "day2",
    name: "스노로즈",
    category: "체험/이벤트 · 굿즈 판매",
    description: "스노로즈 — 나만의 로고 꾸미기 체험과 한정판 굿즈 현장 판매",
    menu: ["티셔츠 18,000원", "반다나 5,500원", "타투스티커 4,400원"],
    events: [
      "로고 꾸미기 — 학생증 확인 시 5P 지급",
      "인스타 스토리 인증 20P / 후기 게시글 인증 20P",
    ],
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "a07-day2",
    locationId: "a07",
    date: "day2",
    name: "프랑스언어문화학과 학생회 더불어",
  },
  {
    id: "a08-day2",
    locationId: "a08",
    date: "day2",
    name: "프랑스언어문화학과 학생회 더불어",
  },
  {
    id: "a09-day2",
    locationId: "a09",
    date: "day2",
    name: "숙명유도부",
  },
  {
    id: "a10-day2",
    locationId: "a10",
    date: "day2",
    name: "반극회",
  },
  {
    id: "a11-day2",
    locationId: "a11",
    date: "day2",
    name: "데스티니",
    category: "공연/이벤트",
    description: "DESTINY SUMMER FESTIVAL — 밴드 데스티니 부스 운영",
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "a12-day2",
    locationId: "a12",
    date: "day2",
    name: "데스티니",
    category: "공연/이벤트",
    description: "DESTINY SUMMER FESTIVAL — 밴드 데스티니 부스 운영",
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "b01-day1",
    locationId: "b01",
    date: "day1",
    name: "숙미회",
    category: "굿즈 판매 · 이벤트",
    description:
      "중앙사진동아리 숙미회 — 부원들이 직접 찍고 제작한 특별한 사진 굿즈 판매",
    events: ["인스타그램(smwu_sook.mi) 팔로우 시 예쁜 스티커 증정"],
    operatingHours: "9/16~9/17 10:00~16:00",
  },
  {
    id: "b02-day1",
    locationId: "b02",
    date: "day1",
    name: "숙미회",
    category: "굿즈 판매 · 이벤트",
    description:
      "중앙사진동아리 숙미회 — 부원들이 직접 찍고 제작한 특별한 사진 굿즈 판매",
    events: ["인스타그램(smwu_sook.mi) 팔로우 시 예쁜 스티커 증정"],
    operatingHours: "9/16~9/17 10:00~16:00",
  },
  {
    id: "b03-day1",
    locationId: "b03",
    date: "day1",
    name: "숙명옴부즈맨 블룸",
    category: "체험/이벤트 · 굿즈 판매",
    description: "숙명 옴부즈맨 블룸 — 숙명인들의 여왕님 도안 제작 타투샵 운영",
    menu: ["타투스티커 1장당 3,500원"],
    events: [
      "숙명 옴부즈맨 블룸 인스타그램 팔로우 시 3,000원 할인 (하루 디자인당 20장, 총 40장 한정)",
    ],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "b04-day1",
    locationId: "b04",
    date: "day1",
    name: "한국어문학부 학회 글마실",
    category: "굿즈 판매 · 이벤트",
    description:
      "한국어문학부 학회 글마실 — 2026 여름문집 <우람바라의 투시도> 및 관련 굿즈 판매, 운세 뽑기 이벤트 진행",
    menu: [
      "미니 인터뷰집 <우람바라의 투시도> 4,000원 (48p)",
      "모조지 칼선 스티커 세트 1,500원 (2장)",
    ],
    events: [
      "글과 함께 운세 뽑기 (500원 / 1회)",
      "글마실 인스타그램 팔로우 시 운세 뽑기 1회 무료 체험",
      "<우리의 우람바라> 포스트잇 이야기 작성 후 인스타 업로드 시 간식 증정",
    ],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "b05-day1",
    locationId: "b05",
    date: "day1",
    name: "숙명통신원",
    category: "굿즈 판매",
    description:
      "숙명통신원 — 숙통 사무소 운영, 스티커 판매와 팔로우 이벤트 진행",
    menu: ["스티커 2,500원 (A6 사이즈, 칼선)"],
    events: [
      "숙명여자대학교·눈송이 인스타그램 모두 팔로우 시 눈송이 굿즈 증정",
    ],
    operatingHours: "9월 16일(수) 10:00~16:00",
  },
  {
    id: "b06-day1",
    locationId: "b06",
    date: "day1",
    name: "숙명통신원",
    category: "굿즈 판매",
    description:
      "숙명통신원 — 숙통 사무소 운영, 스티커 판매와 팔로우 이벤트 진행",
    menu: ["스티커 2,500원 (A6 사이즈, 칼선)"],
    events: [
      "숙명여자대학교·눈송이 인스타그램 모두 팔로우 시 눈송이 굿즈 증정",
    ],
    operatingHours: "9월 16일(수) 10:00~16:00",
  },
  {
    id: "b01-day2",
    locationId: "b01",
    date: "day2",
    name: "숙미회",
    category: "굿즈 판매 · 이벤트",
    description:
      "중앙사진동아리 숙미회 — 부원들이 직접 찍고 제작한 특별한 사진 굿즈 판매",
    events: ["인스타그램(smwu_sook.mi) 팔로우 시 예쁜 스티커 증정"],
    operatingHours: "9/16~9/17 10:00~16:00",
  },
  {
    id: "b02-day2",
    locationId: "b02",
    date: "day2",
    name: "숙미회",
    category: "굿즈 판매 · 이벤트",
    description:
      "중앙사진동아리 숙미회 — 부원들이 직접 찍고 제작한 특별한 사진 굿즈 판매",
    events: ["인스타그램(smwu_sook.mi) 팔로우 시 예쁜 스티커 증정"],
    operatingHours: "9/16~9/17 10:00~16:00",
  },
  {
    id: "b03-day2",
    locationId: "b03",
    date: "day2",
    name: "숙명옴부즈맨 블룸",
    category: "체험/이벤트 · 굿즈 판매",
    description: "숙명 옴부즈맨 블룸 — 숙명인들의 여왕님 도안 제작 타투샵 운영",
    menu: ["타투스티커 1장당 3,500원"],
    events: ["숙명 옴부즈맨 블룸 인스타그램 팔로우 시 3,000원 할인"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "b04-day2",
    locationId: "b04",
    date: "day2",
    name: "so9chi2",
  },
  {
    id: "b05-day2",
    locationId: "b05",
    date: "day2",
    name: "URINK",
    category: "체험/이벤트",
    description:
      "국제협력팀 소속 글로벌 버디 리더십그룹 URINK — 세계 언어·문화 게임과 교환학생-재학생 매칭 이벤트 운영",
    events: [
      "세계 언어·문화 게임",
      "U&I 링킹 부스 — 포스트잇 자기소개 작성 후 교환학생/재학생 매칭",
    ],
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "b06-day2",
    locationId: "b06",
    date: "day2",
    name: "URINK",
    category: "체험/이벤트",
    description:
      "국제협력팀 소속 글로벌 버디 리더십그룹 URINK — 세계 언어·문화 게임과 교환학생-재학생 매칭 이벤트 운영",
    events: [
      "세계 언어·문화 게임",
      "U&I 링킹 부스 — 포스트잇 자기소개 작성 후 교환학생/재학생 매칭",
    ],
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "c01-day1-day",
    locationId: "c01",
    date: "day1",
    session: "day",
    name: "경영학술부",
    category: "먹거리 · 굿즈 판매",
    description:
      "경영학술부(SASB) — 미니 마카롱 우유 말먹 세트 및 행운의 거북이 파츠 판매 부스",
    menu: [
      "미니 마카롱 우유 말먹 세트",
      "행운의 거북이 파츠 500원 (휴대폰 케이스 등 즉석 부착 서비스)",
    ],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "c02-day1-day",
    locationId: "c02",
    date: "day1",
    session: "day",
    name: "경영학술부",
    category: "먹거리 · 굿즈 판매",
    description:
      "경영학술부(SASB) — 미니 마카롱 우유 말먹 세트 및 행운의 거북이 파츠 판매 부스",
    menu: [
      "미니 마카롱 우유 말먹 세트",
      "행운의 거북이 파츠 500원 (휴대폰 케이스 등 즉석 부착 서비스)",
    ],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "c03-day1-day",
    locationId: "c03",
    date: "day1",
    session: "day",
    name: "공예과 금속학회 DOT",
    category: "굿즈 판매 · 이벤트",
    description:
      "금속학회 DOT — 용의 둥지 부스, 보물(금속 공예품) 판매 및 나만의 보물 자랑 이벤트",
    events: ["용의 보물을 구매한 분들을 위한 나만의 보물 자랑 이벤트 진행"],
    operatingHours: "9.16~09.17 10:00~16:00",
  },
  {
    id: "c04-day1-day",
    locationId: "c04",
    date: "day1",
    session: "day",
    name: "공예과 금속학회 DOT",
    category: "굿즈 판매 · 이벤트",
    description:
      "금속학회 DOT — 용의 둥지 부스, 보물(금속 공예품) 판매 및 나만의 보물 자랑 이벤트",
    events: ["용의 보물을 구매한 분들을 위한 나만의 보물 자랑 이벤트 진행"],
    operatingHours: "9.16~09.17 10:00~16:00",
  },
  {
    id: "c05-day1-day",
    locationId: "c05",
    date: "day1",
    session: "day",
    name: "SCSM",
    category: "굿즈 판매 · 게임",
    description: "SCSM — 바다 콘셉트의 MD 판매 및 낚시 게임 부스",
    menu: [
      "킥판 키링 3,000원",
      "해양생물 키링 1,000원~1,500원",
      "스티커 3종 500원~1,000원",
    ],
    events: ["물 위 물고기를 잡는 낚시 게임 참여 후 경품 획득"],
    operatingHours: "9/16(수) 10:00~20:00",
  },
  {
    id: "c06-day1-day",
    locationId: "c06",
    date: "day1",
    session: "day",
    name: "SCSM",
    category: "굿즈 판매 · 게임",
    description: "SCSM — 바다 콘셉트의 MD 판매 및 낚시 게임 부스",
    menu: [
      "킥판 키링 3,000원",
      "해양생물 키링 1,000원~1,500원",
      "스티커 3종 500원~1,000원",
    ],
    events: ["물 위 물고기를 잡는 낚시 게임 참여 후 경품 획득"],
    operatingHours: "9/16(수) 10:00~20:00",
  },
  {
    id: "c07-day1-day",
    locationId: "c07",
    date: "day1",
    session: "day",
    name: "UNSA",
    category: "굿즈 판매",
    description:
      "숙명여대 유엔한국학생협회(UNSA-ROK) — 바다를 품은 키링, 나만의 지퍼백 키링 제작 부스",
    menu: [
      "지퍼백 키링 3,000원",
      "행운의 거북이 부착 500원 (키링 제작 시 거북이 부착 S/V)",
    ],
    operatingHours: "9/16(수) 10:00~17:00",
  },
  {
    id: "c08-day1-day",
    locationId: "c08",
    date: "day1",
    session: "day",
    name: "UNSA",
    category: "굿즈 판매",
    description:
      "숙명여대 유엔한국학생협회(UNSA-ROK) — 바다를 품은 키링, 나만의 지퍼백 키링 제작 부스",
    menu: [
      "지퍼백 키링 3,000원",
      "행운의 거북이 부착 500원 (키링 제작 시 거북이 부착 S/V)",
    ],
    operatingHours: "9/16(수) 10:00~17:00",
  },
  {
    id: "c09-day1-day",
    locationId: "c09",
    date: "day1",
    session: "day",
    name: "경영연구학회 청명",
    category: "굿즈 판매 · 이벤트",
    description:
      "경영연구학회 청명 & 종강대책위원회 — 눈송이 떡메모지 3종, 긴급탈출 키캡 키링 및 Team Gemini 컬래버 이벤트 부스",
    menu: [
      "송이의 시험기간 3종 처방전 (떡메모지) 2,500원 (수요조사 인증 시 2,000원 할인)",
      "긴급탈출 키캡키링 (과제 DELETE, 학점 F5, 인생 F5) 3,500원",
    ],
    events: [
      "Google AI Sign-up 인증 이벤트 — 팀 제미니 링크 가입 후 인증 시 더베이크 눈송이 쿠키 증정 및 선착순 30명 5,000원권 증정",
      "다트 던지기 2회 무료 기회 제공",
    ],
    operatingHours: "9월 16일(수) 10:00~18:00",
  },
  {
    id: "c10-day1-day",
    locationId: "c10",
    date: "day1",
    session: "day",
    name: "경영연구학회 청명",
    category: "굿즈 판매 · 이벤트",
    description:
      "경영연구학회 청명 & 종강대책위원회 — 눈송이 떡메모지 3종, 긴급탈출 키캡 키링 및 Team Gemini 컬래버 이벤트 부스",
    menu: [
      "송이의 시험기간 3종 처방전 (떡메모지) 2,500원 (수요조사 인증 시 2,000원 할인)",
      "긴급탈출 키캡키링 (과제 DELETE, 학점 F5, 인생 F5) 3,500원",
    ],
    events: [
      "Google AI Sign-up 인증 이벤트 — 팀 제미니 링크 가입 후 인증 시 더베이크 눈송이 쿠키 증정 및 선착순 30명 5,000원권 증정",
      "다트 던지기 2회 무료 기회 제공",
    ],
    operatingHours: "9월 16일(수) 10:00~18:00",
  },
  {
    id: "c11-day1-day",
    locationId: "c11",
    date: "day1",
    session: "day",
    name: "경영학부 학회 향영",
    category: "체험/이벤트",
    description:
      "숙명여자대학교 경영학부 학회 향영 — 고무피부터 파츠까지 직접 골라 만드는 나만의 말랑이 제작 체험 부스",
    menu: [
      "고무피 선택 (곰발바닥, 큰 원, 작은 원, 하트) 5,000원 / 6,000원",
      "파츠 꾸미기 (눈송이, 거북이, 네잎클로버 등 약 20종) 800원~1,500원",
    ],
    operatingHours: "9월 16일(수) 10:00~20:00",
  },
  {
    id: "c12-day1-day",
    locationId: "c12",
    date: "day1",
    session: "day",
    name: "경영학부 학회 향영",
    category: "체험/이벤트",
    description:
      "숙명여자대학교 경영학부 학회 향영 — 고무피부터 파츠까지 직접 골라 만드는 나만의 말랑이 제작 체험 부스",
    menu: [
      "고무피 선택 (곰발바닥, 큰 원, 작은 원, 하트) 5,000원 / 6,000원",
      "파츠 꾸미기 (눈송이, 거북이, 네잎클로버 등 약 20종) 800원~1,500원",
    ],
    operatingHours: "9월 16일(수) 10:00~20:00",
  },
  {
    id: "c01-day1-night",
    locationId: "c01",
    date: "day1",
    session: "night",
    name: "엉뚱한 사람들",
  },
  {
    id: "c02-day1-night",
    locationId: "c02",
    date: "day1",
    session: "night",
    name: "엉뚱한 사람들",
  },
  {
    id: "c03-day1-night",
    locationId: "c03",
    date: "day1",
    session: "night",
    name: "설미",
  },
  {
    id: "c04-day1-night",
    locationId: "c04",
    date: "day1",
    session: "night",
    name: "설미",
  },
  {
    id: "c05-day1-night",
    locationId: "c05",
    date: "day1",
    session: "night",
    name: "SCSM",
  },
  {
    id: "c06-day1-night",
    locationId: "c06",
    date: "day1",
    session: "night",
    name: "SCSM",
  },
  {
    id: "c07-day1-night",
    locationId: "c07",
    date: "day1",
    session: "night",
    name: "UNSA",
  },
  {
    id: "c08-day1-night",
    locationId: "c08",
    date: "day1",
    session: "night",
    name: "UNSA",
  },
  {
    id: "c09-day1-night",
    locationId: "c09",
    date: "day1",
    session: "night",
    name: "경영연구학회 청명",
  },
  {
    id: "c10-day1-night",
    locationId: "c10",
    date: "day1",
    session: "night",
    name: "경영연구학회 청명",
  },
  {
    id: "c11-day1-night",
    locationId: "c11",
    date: "day1",
    session: "night",
    name: "경영학부 학회 향영",
  },
  {
    id: "c12-day1-night",
    locationId: "c12",
    date: "day1",
    session: "night",
    name: "경영학부 학회 향영",
  },
  {
    id: "c01-day2-day",
    locationId: "c01",
    date: "day2",
    session: "day",
    name: "경영학술부",
    category: "먹거리 · 굿즈 판매",
    description:
      "경영학술부(SASB) — 미니 마카롱 우유 말먹 세트 및 행운의 거북이 파츠 판매 부스",
    menu: ["미니 마카롱 우유 말먹 세트", "행운의 거북이 파츠 500원"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "c02-day2-day",
    locationId: "c02",
    date: "day2",
    session: "day",
    name: "경영학술부",
    category: "먹거리 · 굿즈 판매",
    description:
      "경영학술부(SASB) — 미니 마카롱 우유 말먹 세트 및 행운의 거북이 파츠 판매 부스",
    menu: ["미니 마카롱 우유 말먹 세트", "행운의 거북이 파츠 500원"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "c03-day2-day",
    locationId: "c03",
    date: "day2",
    session: "day",
    name: "공예과 금속학회 DOT",
    category: "굿즈 판매 · 이벤트",
    description: "금속학회 DOT — 용의 둥지 부스",
    operatingHours: "9.16~09.17 10:00~16:00",
  },
  {
    id: "c04-day2-day",
    locationId: "c04",
    date: "day2",
    session: "day",
    name: "공예과 금속학회 DOT",
    category: "굿즈 판매 · 이벤트",
    description: "금속학회 DOT — 용의 둥지 부스",
    operatingHours: "9.16~09.17 10:00~16:00",
  },
  {
    id: "c05-day2-day",
    locationId: "c05",
    date: "day2",
    session: "day",
    name: "교육방송국 SBS",
  },
  {
    id: "c06-day2-day",
    locationId: "c06",
    date: "day2",
    session: "day",
    name: "교육방송국 SBS",
  },
  {
    id: "c07-day2-day",
    locationId: "c07",
    date: "day2",
    session: "day",
    name: "배숙켓볼",
  },
  {
    id: "c08-day2-day",
    locationId: "c08",
    date: "day2",
    session: "day",
    name: "MAX",
  },
  {
    id: "c09-day2-day",
    locationId: "c09",
    date: "day2",
    session: "day",
    name: "경영연구학회 청명",
  },
  {
    id: "c10-day2-day",
    locationId: "c10",
    date: "day2",
    session: "day",
    name: "경영연구학회 청명",
  },
  {
    id: "c11-day2-day",
    locationId: "c11",
    date: "day2",
    session: "day",
    name: "경영학부 학회 향영",
  },
  {
    id: "c12-day2-day",
    locationId: "c12",
    date: "day2",
    session: "day",
    name: "경영학부 학회 향영",
  },
  {
    id: "c11-day2-night",
    locationId: "c11",
    date: "day2",
    session: "night",
    name: "구름바다햇살",
    category: "굿즈 판매",
    description:
      "구름바다햇살 — 직접 찍은 사진으로 제작한 엽서 및 폰 배경화면 판매",
    menu: [
      "엽서 각 1,500원 (5장 구매 시 6,000원, 10장 구매 시 10,000원)",
      "폰 배경화면 세트당 500원",
    ],
    operatingHours: "목요일 16:30~20:00",
  },
  {
    id: "c12-day2-night",
    locationId: "c12",
    date: "day2",
    session: "night",
    name: "구름바다햇살",
    category: "굿즈 판매",
    description:
      "구름바다햇살 — 직접 찍은 사진으로 제작한 엽서 및 폰 배경화면 판매",
    menu: [
      "엽서 각 1,500원 (5장 구매 시 6,000원, 10장 구매 시 10,000원)",
      "폰 배경화면 세트당 500원",
    ],
    operatingHours: "목요일 16:30~20:00",
  },
  {
    id: "d01-day1",
    locationId: "d01",
    date: "day1",
    name: "섬유학회 SAI",
    category: "굿즈 판매 · 이벤트",
    description:
      "섬유학회 SAI — 매듭과 비즈 키링, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 참여"],
    operatingHours: "09.16~09.17 10:00~16:00",
  },
  {
    id: "d02-day1",
    locationId: "d02",
    date: "day1",
    name: "섬유학회 SAI",
    category: "굿즈 판매 · 이벤트",
    description:
      "섬유학회 SAI — 매듭과 비즈 키링, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 참여"],
    operatingHours: "09.16~09.17 10:00~16:00",
  },
  {
    id: "d03-day1",
    locationId: "d03",
    date: "day1",
    name: "SAA",
    category: "굿즈 판매 · 이벤트",
    description:
      "SAA 구슬다락방 — 가을 색을 담은 오색빛 구슬 팔찌와 무화과 끈 팔찌 판매",
    menu: ["오색빛 구슬 팔찌 4,000원", "무화과 끈 팔찌 4,000원"],
    events: ["한정 수량 럭키드로우 이벤트 진행"],
    operatingHours: "09.16~09.17 10:00~16:00",
  },
  {
    id: "d04-day1",
    locationId: "d04",
    date: "day1",
    name: "숙불회",
    category: "체험/이벤트",
    description:
      "숙불회 사티클럽 — 향기와 명상을 통한 힐링 체험, 종교 무관 무료 참여",
    events: ["매일 선착순 80명 굿즈 스티커 증정"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "d05-day1",
    locationId: "d05",
    date: "day1",
    name: "숙파이크",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "숙파이크 — 순발력 게임 및 서전트 점프 측정, 귀여운 굿즈 판매 부스",
    menu: [
      "고양이 키링(4종) 3,500원",
      "배구공·네잎클로버·토마토 키링 3,000~4,000원",
      "동물 키링(5종) 5,000원",
    ],
    events: ["GAME 1) 순발력 게임 (막대 잡기)", "GAME 2) 서전트 점프 측정"],
    operatingHours: "9/16(수) 10:00~16:00",
  },
  {
    id: "d06-day1",
    locationId: "d06",
    date: "day1",
    name: "숙파이크",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "숙파이크 — 순발력 게임 및 서전트 점프 측정, 귀여운 굿즈 판매 부스",
    menu: [
      "고양이 키링(4종) 3,500원",
      "배구공·네잎클로버·토마토 키링 3,000~4,000원",
      "동물 키링(5종) 5,000원",
    ],
    events: ["GAME 1) 순발력 게임 (막대 잡기)", "GAME 2) 서전트 점프 측정"],
    operatingHours: "9/16(수) 10:00~16:00",
  },
  {
    id: "d07-day1",
    locationId: "d07",
    date: "day1",
    name: "육군ROTC",
  },
  {
    id: "d08-day1",
    locationId: "d08",
    date: "day1",
    name: "육군ROTC",
  },
  {
    id: "d01-day2",
    locationId: "d01",
    date: "day2",
    name: "섬유학회 SAI",
    category: "굿즈 판매 · 이벤트",
    description:
      "섬유학회 SAI — 매듭과 비즈 키링, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 참여"],
    operatingHours: "09.16~09.17 10:00~16:00",
  },
  {
    id: "d02-day2",
    locationId: "d02",
    date: "day2",
    name: "섬유학회 SAI",
    category: "굿즈 판매 · 이벤트",
    description:
      "섬유학회 SAI — 매듭과 비즈 키링, 패브릭 케이블 홀더 판매 및 럭키드로우",
    menu: [
      "매듭 참 6,000원",
      "장식 매듭 참 8,000원",
      "패브릭 케이블 홀더 3,000원",
    ],
    events: ["SAI 공식 인스타그램 팔로우 시 꽝 없는 럭키드로우 참여"],
    operatingHours: "09.16~09.17 10:00~16:00",
  },
  {
    id: "d03-day2",
    locationId: "d03",
    date: "day2",
    name: "SAA",
    category: "굿즈 판매 · 이벤트",
    description:
      "SAA 구슬다락방 — 가을 색을 담은 오색빛 구슬 팔찌와 무화과 끈 팔찌 판매",
    menu: ["오색빛 구슬 팔찌 4,000원", "무화과 끈 팔찌 4,000원"],
    events: ["한정 수량 럭키드로우 이벤트 진행"],
    operatingHours: "09.16~09.17 10:00~16:00",
  },
  {
    id: "d04-day2",
    locationId: "d04",
    date: "day2",
    name: "숙불회",
    category: "체험/이벤트",
    description:
      "숙불회 사티클럽 — 향기와 명상을 통한 힐링 체험, 종교 무관 무료 참여",
    events: ["매일 선착순 80명 굿즈 스티커 증정"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "d05-day2",
    locationId: "d05",
    date: "day2",
    name: "코드 BLUE",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "중앙 통기타&어쿠스틱 공연동아리 코드BLUE — CHORD RED RED 해제 음악 게임 및 굿즈 뽑기 부스",
    events: [
      "1단계 1초 듣고 노래 맞히기 (전통 간식 꾸러미)",
      "2단계 AI 가사 맞히기 (코드블루 눈송이 스티커)",
      "3단계 믹스 노래 키즈 또는 절대 음감 게임 (비눗방울 + 럭키드로우 뽑기권)",
      "럭키드로우 1등 말랑이, 2등 키캡 키링, 3등 자체제작 눈송이 메모지",
    ],
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "d06-day2",
    locationId: "d06",
    date: "day2",
    name: "코드 BLUE",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "중앙 통기타&어쿠스틱 공연동아리 코드BLUE — CHORD RED RED 해제 음악 게임 및 굿즈 뽑기 부스",
    events: [
      "1단계 1초 듣고 노래 맞히기 (전통 간식 꾸러미)",
      "2단계 AI 가사 맞히기 (코드블루 눈송이 스티커)",
      "3단계 믹스 노래 키즈 또는 절대 음감 게임 (비눗방울 + 럭키드로우 뽑기권)",
      "럭키드로우 1등 말랑이, 2등 키캡 키링, 3등 자체제작 눈송이 메모지",
    ],
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "d07-day2",
    locationId: "d07",
    date: "day2",
    name: "육군ROTC",
  },
  {
    id: "d08-day2",
    locationId: "d08",
    date: "day2",
    name: "육군ROTC",
  },
  {
    id: "e01-day1",
    locationId: "e01",
    date: "day1",
    name: "공군학군단",
  },
  {
    id: "e02-day1",
    locationId: "e02",
    date: "day1",
    name: "공군학군단",
  },
  {
    id: "e03-day1",
    locationId: "e03",
    date: "day1",
    name: "로봇학회 RIME",
    category: "체험/이벤트",
    description:
      "로봇학회 RIME — 로봇체험 부스 (로봇팔 캔디샐러드 뽑기, 거미로봇 미션, 휴머노이드 로봇 축구, 로봇카 조종)",
    events: ["로봇 조종 및 미션 수행 시 상품 증정"],
    operatingHours: "10:00-16:00",
  },
  {
    id: "e04-day1",
    locationId: "e04",
    date: "day1",
    name: "로봇학회 RIME",
    category: "체험/이벤트",
    description:
      "로봇학회 RIME — 로봇체험 부스 (로봇팔 캔디샐러드 뽑기, 거미로봇 미션, 휴머노이드 로봇 축구, 로봇카 조종)",
    events: ["로봇 조종 및 미션 수행 시 상품 증정"],
    operatingHours: "10:00-16:00",
  },
  {
    id: "e05-day1",
    locationId: "e05",
    date: "day1",
    name: "숙명 CCC",
  },
  {
    id: "e06-day1",
    locationId: "e06",
    date: "day1",
    name: "숙명 CCC",
  },
  {
    id: "e07-day1",
    locationId: "e07",
    date: "day1",
    name: "숙명입학홍보대사 폴라리스",
    category: "먹거리",
    description:
      "폴송이의 아이스크림 가게 — 밀크 폴스크림에 초코쉘·시리얼 등 다양한 토핑을 취향대로 올려 즐기는 부스",
    menu: [
      "초코바나나 세트 2,500원",
      "폴바나나 세트 2,800원",
      "폴송이 PICK 3,200원",
    ],
    posterImages: ["/assets/posters/e07-e08-polaris.png"],
  },
  {
    id: "e08-day1",
    locationId: "e08",
    date: "day1",
    name: "숙명입학홍보대사 폴라리스",
    category: "먹거리",
    description:
      "폴송이의 아이스크림 가게 — 밀크 폴스크림에 초코쉘·시리얼 등 다양한 토핑을 취향대로 올려 즐기는 부스",
    menu: [
      "초코바나나 세트 2,500원",
      "폴바나나 세트 2,800원",
      "폴송이 PICK 3,200원",
    ],
    posterImages: ["/assets/posters/e07-e08-polaris.png"],
  },
  {
    id: "e09-day1",
    locationId: "e09",
    date: "day1",
    name: "공예과 도자학회 아람",
    category: "굿즈 판매",
    description:
      "도자학회 아람 — 컵, 접시 등 식기류부터 목걸이 등 악세사리, 워리스톤과 키링 등 도자 작업물 판매",
    operatingHours: "9월 16일~9월 17일 10:00~16:00",
  },
  {
    id: "e10-day1",
    locationId: "e10",
    date: "day1",
    name: "숙명문화봉사단",
    category: "굿즈 판매 · 이벤트",
    description:
      "숙명문화봉사단 — [황실로부터의 초대] 주제 부스, 대한제국 오얏꽃 스크런치, 노리개, 키캡, 박물관 티셔츠 판매",
    menu: [
      "대한제국 오얏꽃 스크런치 3,500원",
      "눈꽃·오얏꽃 노리개 4,000원",
      "창학 120주년 기념 키캡 9,000원",
      "박물관 티셔츠 15,000원",
    ],
    events: [
      "인스타그램 팔로우 또는 스토리 업로드 시 간식 증정",
      "문봉 퀴즈 이벤트 (상/하 난이도 문제 정답 시 띠부띠부씰 또는 책갈피 증정)",
      "눈송이 투어 얼리버드 신청 시 간식 증정",
    ],
    operatingHours: "9월 16일(수), 9월 17일(목) 9:00~16:30",
  },
  {
    id: "e11-day1",
    locationId: "e11",
    date: "day1",
    name: "로타랙트",
    category: "체험/이벤트",
    description:
      "숙명로타랙트 — 쿠키 DIY 및 기부용 쿠키 만들기 부스 (아동복지시설 혜심원 전달)",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원"],
    events: ["기부용 쿠키 구매 후 아이싱펜과 스프링클로 꾸며 부스에 전달"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "e12-day1",
    locationId: "e12",
    date: "day1",
    name: "로타랙트",
    category: "체험/이벤트",
    description:
      "숙명로타랙트 — 쿠키 DIY 및 기부용 쿠키 만들기 부스 (아동복지시설 혜심원 전달)",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원"],
    events: ["기부용 쿠키 구매 후 아이싱펜과 스프링클로 꾸며 부스에 전달"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "e13-day1",
    locationId: "e13",
    date: "day1",
    name: "자유전공학부 학생자치위원회 비상대책위원회",
    category: "체험/이벤트",
    description:
      "축제 상황에 맞춘 12문항 테스트로 나만의 축제 MBTI(눈송이 테마 16유형)를 찾고, 결과에 맞는 초콜릿으로 간식컵을 완성하는 체험형 부스",
    menu: ["간식컵 & 럭키드로우 3,000원"],
    events: [
      "럭키드로우 — 간식컵 바닥 랜덤 스티커, 본인 테스트 결과와 일치 시 선착순 경품",
    ],
    operatingHours: "2026.09.16~09.17 10:00~16:00",
    posterImages: ["/assets/posters/e13-mbti.png"],
  },
  {
    id: "e14-day1",
    locationId: "e14",
    date: "day1",
    name: "숙명지식봉사단",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "숙명지식봉사단 — 지봉키캡공방 운영, 나만의 커스텀 키캡 제작 체험 (수익금 전액 소외계층 아동 교육 여건 개선 기부)",
    menu: ["지봉 키캡 제작 5,000원 (이벤트 참여 시 10% 할인)"],
    events: ["지봉 행복 풍선 꾸미기 활동"],
    operatingHours: "2026년 9월 16일 수요일 10:00-16:00",
  },
  {
    id: "e15-day1",
    locationId: "e15",
    date: "day1",
    name: "이과대학 학생회 SEQUENCE",
    category: "체험/이벤트",
    description:
      "「행운 연구소」 — 인간 팩맨 게임으로 행운 수치를 측정하고, 충전 음료와 네컷 촬영까지 즐기는 체험 부스",
    menu: [
      "행운 충전 용액(레몬 에이드) 2,500원",
      "행복 충전 용액(자몽 에이드) 2,500원",
      "용기 충전 용액(청포도 에이드) 2,500원",
    ],
    events: [
      "행운 실험실 — 인간 팩맨 게임 3,000원",
      "행운 기록실 — 네컷 프레임 촬영 1,000원",
    ],
    operatingHours: "9월 16일(수) 10:00~16:00",
    posterImages: ["/assets/posters/e15-e16-sequence.png"],
  },
  {
    id: "e16-day1",
    locationId: "e16",
    date: "day1",
    name: "이과대학 학생회 SEQUENCE",
    category: "체험/이벤트",
    description:
      "「행운 연구소」 — 인간 팩맨 게임으로 행운 수치를 측정하고, 충전 음료와 네컷 촬영까지 즐기는 체험 부스",
    menu: [
      "행운 충전 용액(레몬 에이드) 2,500원",
      "행복 충전 용액(자몽 에이드) 2,500원",
      "용기 충전 용액(청포도 에이드) 2,500원",
    ],
    events: [
      "행운 실험실 — 인간 팩맨 게임 3,000원",
      "행운 기록실 — 네컷 프레임 촬영 1,000원",
    ],
    operatingHours: "9월 16일(수) 10:00~16:00",
    posterImages: ["/assets/posters/e15-e16-sequence.png"],
  },
  {
    id: "e17-day1",
    locationId: "e17",
    date: "day1",
    name: "문헌정보학과 학생회 온결",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "숙명문정도서전 — 나만의 책 MBTI [북BTI] 및 영롱한 끈갈피 만들기 체험, 굿즈 판매",
    menu: [
      "종이부채 2종 각 1,000원",
      "독사가를 위한 스티커 3종 세트 3,000원",
      "DIY 끈갈피 개당 6,000원 (체험 시 4,000원)",
    ],
    events: ["북BTI 테스트 결과 인스타 공유 시 맞춤형 책갈피 증정"],
    operatingHours: "09.16(수) 10:00~16:00",
  },
  {
    id: "e18-day1",
    locationId: "e18",
    date: "day1",
    name: "문헌정보학과 학생회 온결",
    category: "체험/이벤트 · 굿즈 판매",
    description:
      "숙명문정도서전 — 나만의 책 MBTI [북BTI] 및 영롱한 끈갈피 만들기 체험, 굿즈 판매",
    menu: [
      "종이부채 2종 각 1,000원",
      "독사가를 위한 스티커 3종 세트 3,000원",
      "DIY 끈갈피 개당 6,000원 (체험 시 4,000원)",
    ],
    events: ["북BTI 테스트 결과 인스타 공유 시 맞춤형 책갈피 증정"],
    operatingHours: "09.16(수) 10:00~16:00",
  },
  {
    id: "e19-day1",
    locationId: "e19",
    date: "day1",
    name: "묵아랑",
  },
  {
    id: "e20-day1",
    locationId: "e20",
    date: "day1",
    name: "묵아랑",
  },
  {
    id: "e01-day2",
    locationId: "e01",
    date: "day2",
    name: "공군학군단",
  },
  {
    id: "e02-day2",
    locationId: "e02",
    date: "day2",
    name: "공군학군단",
  },
  {
    id: "e03-day2",
    locationId: "e03",
    date: "day2",
    name: "설미",
  },
  {
    id: "e04-day2",
    locationId: "e04",
    date: "day2",
    name: "설미",
  },
  {
    id: "e05-day2",
    locationId: "e05",
    date: "day2",
    name: "숙명 CCC",
  },
  {
    id: "e06-day2",
    locationId: "e06",
    date: "day2",
    name: "숙명 CCC",
  },
  {
    id: "e07-day2",
    locationId: "e07",
    date: "day2",
    name: "숙명입학홍보대사 폴라리스",
    category: "먹거리",
    description:
      "폴송이의 아이스크림 가게 — 밀크 폴스크림에 초코쉘·시리얼 등 다양한 토핑을 취향대로 올려 즐기는 부스",
    menu: [
      "초코바나나 세트 2,500원",
      "폴바나나 세트 2,800원",
      "폴송이 PICK 3,200원",
    ],
    posterImages: ["/assets/posters/e07-e08-polaris.png"],
  },
  {
    id: "e08-day2",
    locationId: "e08",
    date: "day2",
    name: "숙명입학홍보대사 폴라리스",
    category: "먹거리",
    description:
      "폴송이의 아이스크림 가게 — 밀크 폴스크림에 초코쉘·시리얼 등 다양한 토핑을 취향대로 올려 즐기는 부스",
    menu: [
      "초코바나나 세트 2,500원",
      "폴바나나 세트 2,800원",
      "폴송이 PICK 3,200원",
    ],
    posterImages: ["/assets/posters/e07-e08-polaris.png"],
  },
  {
    id: "e09-day2",
    locationId: "e09",
    date: "day2",
    name: "공예과 도자학회 아람",
    category: "굿즈 판매",
    description: "도자학회 아람 — 도자 작업물 판매",
    operatingHours: "9월 16일~9월 17일 10:00~16:00",
  },
  {
    id: "e10-day2",
    locationId: "e10",
    date: "day2",
    name: "반극회",
  },
  {
    id: "e11-day2",
    locationId: "e11",
    date: "day2",
    name: "로타랙트",
    category: "체험/이벤트",
    description: "숙명로타랙트 — 쿠키 DIY 및 기부용 쿠키 만들기 부스",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "e12-day2",
    locationId: "e12",
    date: "day2",
    name: "로타랙트",
    category: "체험/이벤트",
    description: "숙명로타랙트 — 쿠키 DIY 및 기부용 쿠키 만들기 부스",
    menu: ["일반 쿠키 2,500원", "기부용 쿠키 2,000원"],
    operatingHours: "9월 16일(수)~17일(목) 10:00~16:00",
  },
  {
    id: "e13-day2",
    locationId: "e13",
    date: "day2",
    name: "자유전공학부 학생자치위원회 비상대책위원회",
    category: "체험/이벤트",
    description:
      "축제 상황에 맞춘 12문항 테스트로 나만의 축제 MBTI를 찾고 간식컵을 완성하는 체험형 부스",
    menu: ["간식컵 & 럭키드로우 3,000원"],
    operatingHours: "2026.09.16~09.17 10:00~16:00",
  },
  {
    id: "e14-day2",
    locationId: "e14",
    date: "day2",
    name: "스마티어",
    category: "체험/이벤트",
    description:
      "중앙도서관 리더십그룹 스마티어 — 스마티어 마법소, 독서 레벨 측정 및 마법 물품 소장 이벤트",
    operatingHours: "9월 17일(목) 10:00~16:00",
  },
  {
    id: "e15-day2",
    locationId: "e15",
    date: "day2",
    name: "역사문화학과 학생회 사랑",
  },
  {
    id: "e16-day2",
    locationId: "e16",
    date: "day2",
    name: "역사문화학과 학생회 사랑",
  },
  {
    id: "e17-day2",
    locationId: "e17",
    date: "day2",
    name: "왜 저 떠봐요?",
  },
  {
    id: "e18-day2",
    locationId: "e18",
    date: "day2",
    name: "TUMS",
    category: "체험/이벤트",
    description:
      "게임 메타버스 개발 동아리 TUMS — 개발 게임 전시 및 멫챠 카멜레온 피규어 찾기, 뽑기 이벤트",
    events: ["미션 수행 시 간식 및 눈송이 인형 경품 증정 (꽝 없음)"],
    operatingHours: "9월 13일 10:00~16:00",
  },
  {
    id: "e19-day2",
    locationId: "e19",
    date: "day2",
    name: "뜨개송송",
  },
  {
    id: "e20-day2",
    locationId: "e20",
    date: "day2",
    name: "파란",
    category: "동아리 · 굿즈 판매",
    description:
      "숙명여대 자치언론 파란 — 교지 판매 및 타투스티커·포스트잇 이벤트 부스, 숙명사랑해 티셔츠 판매",
    menu: ["신간 파란14호", "숙명사랑해 티셔츠 15,000원", "파란 타투스티커"],
    events: ["타투 스티커 500원", "포스트잇 캠페인 참여 시 야광팔찌 증정"],
    operatingHours: "9월 17일 목요일 10:00~16:00",
  },
];

export const schedules: ScheduleItem[] = [
  {
    date: "day1",
    time: "13:00",
    title: "버스킹 (보컬)",
    place: "제1캠퍼스 원형극장",
    description: "초록공룡 · 체리송이",
  },
  {
    date: "day1",
    time: "14:40",
    title: "버스킹 (밴드)",
    place: "제1캠퍼스 원형극장",
    description: "미정 · 박치더락",
  },
  {
    date: "day1",
    time: "16:10",
    title: "학생 참여팀 무대 공연",
    place: "제1캠퍼스 야외주차장",
    description: "AXIOM · 이카루스 · 코드BLUE · 청월대전 · 설렘 · NIVIS",
  },
  {
    date: "day1",
    time: "18:00",
    title: "청월대전 (학생 참여 노래대회)",
    place: "제1캠퍼스 야외주차장",
    description: "가면 노래대회, 현장 투표로 순위 결정 (시간 변동 가능)",
  },
  {
    date: "day1",
    time: "시간 미정",
    title: "아티스트 무대",
    place: "제1캠퍼스 야외주차장",
    description: "우아 · 스테이씨 · 최예나",
  },
  {
    date: "day2",
    time: "14:30",
    title: "버스킹",
    place: "새힘관 앞 잔디밭",
    description: "설화연 · 숙풍",
  },
  {
    date: "day2",
    time: "16:20",
    title: "학생 참여팀 무대 공연",
    place: "제1캠퍼스 야외주차장",
    description: "DESTINY · 송이무사 · HADA · MAX · 궁중택일",
  },
  {
    date: "day2",
    time: "18:20",
    title: "궁중택일 (밸런스게임 토크쇼)",
    place: "제1캠퍼스 야외주차장 본무대",
    description: "게스트: 김은하 · 허휘수 (동문 유튜버)",
  },
  {
    date: "day2",
    time: "시간 미정",
    title: "아티스트 무대",
    place: "제1캠퍼스 야외주차장",
    description: "힛지스 · 피프티피프티 · 프로미스나인(멤버 지원 불참)",
  },
];