export type Campus = 'campus1' | 'campus2'
export type Day = 'day1' | 'day2'
export type BoothLocation = { id: string; campus: Campus; code: string; latitude: number; longitude: number; mapPosition: { x: number; y: number }; mapSize?: { width: number; height: number }; location: string }
export type Booth = { id: string; locationId: string; date: Day; session?: 'day' | 'night'; source?: 'direct' | 'official'; name: string; category?: string; description?: string; menu?: string[]; events?: string[]; operatingHours?: string; posterImage?: string; posterImages?: string[]; promoLinks?: { instagram?: string; everytime?: string; website?: string } }
export type ScheduleProgram = { time: string; performer: string; content?: string }
export type ScheduleItem = { date: Day; time: string; title: string; place: string; description?: string; programs?: ScheduleProgram[] }
export type Artist = { id: string; day: Day; name: string; note?: string }
export type Notice = { id: string; scope: 'global' | 'location'; title: string; body: string; locationId?: string }
export type FoodTruck = { id: string; name: string; menu: string[] }
export type Ride = { id: string; name: string; location: string; hours: string; capacity: string }
export type PhotoBooth = { id: string; campus: Campus; location: string; hours: string; count: number }
export type Sponsor = { id: string; name: string; description: string; link?: string; linkLabel?: string }
export type OfficialLinks = { instagram: string; email: string; alumniInstagram?: string; barrierFreeEmail?: string; youtube?: string }
